'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {EventEmitter}=require('node:events');const net=require('node:net');
const secondaryRoot=fs.mkdtempSync(path.join(os.tmpdir(),'better-codex-secondary-'));process.env.BETTER_CODEX_WORKSPACE=process.cwd();process.env.BETTER_CODEX_SECONDARY_WORKSPACE=secondaryRoot;const {ScopedBridge}=require('./bridge.cjs');
const threads=new Map([['AI',{id:'AI',cwd:process.cwd()}],['SECONDARY',{id:'SECONDARY',cwd:secondaryRoot}]]);
async function setup(workspace='ai'){
 const dir=fs.mkdtempSync('/tmp/scope-bridge-');const socket=path.join(dir,'h.sock');const srv=net.createServer();await new Promise(r=>srv.listen(socket,r));let captured;const out=[];
 class Fake extends EventEmitter {constructor(url,options){super();captured={url,options,wire:this};this.sent=[];this.loaded=[];queueMicrotask(()=>this.emit('open'))}send(s){const m=JSON.parse(s);this.sent.push(m);if(m.method==='thread/read')queueMicrotask(()=>this.emit('message',Buffer.from(JSON.stringify({id:m.id,result:{thread:threads.get(m.params.threadId)}}))));if(m.method==='thread/loaded/list')queueMicrotask(()=>this.emit('message',Buffer.from(JSON.stringify({id:m.id,result:{data:this.loaded,nextCursor:null}}))));}terminate(){}close(){}}
 const bridge=new ScopedBridge({socket,workspace,WebSocket:Fake,output:m=>out.push(m)});await bridge.ready;return{bridge,out,captured,cleanup:()=>{bridge.close();srv.close()}};
}
const flush=()=>new Promise(r=>setImmediate(r));
test('Unix handshake disables deflate and missing host fails closed',async()=>{const x=await setup();try{assert.equal(x.captured.options.perMessageDeflate,false);assert.throws(()=>new ScopedBridge({socket:'/missing.sock',workspace:'ai'}));}finally{x.cleanup()}});
test('list response and cross-workspace guessed ID are filtered server-side',async()=>{const x=await setup();try{await x.bridge.input({id:1,method:'thread/list',params:{}});await x.bridge.receive({id:1,result:{data:[...threads.values()],nextCursor:null}});assert.deepEqual(x.out[0].result.data.map(t=>t.id),['AI']);await x.bridge.input({id:2,method:'thread/read',params:{threadId:'SECONDARY'}});assert.equal(x.out[1].error.code,-32003);assert.equal(x.captured.wire.sent.filter(m=>m.id===2).length,0);}finally{x.cleanup()}});
test('external history does not grant resume ownership and cwd escape is denied',async()=>{const x=await setup();try{await x.bridge.input({id:1,method:'thread/resume',params:{threadId:'AI'}});await x.bridge.input({id:2,method:'thread/start',params:{cwd:path.join(process.cwd(),'..','SECONDARY')}});assert.equal(x.out.length,2);assert(x.out.every(m=>m.error.code===-32003));}finally{x.cleanup()}});
test('native approval IDs and answers survive and cross-area events do not escape',async()=>{const x=await setup();try{x.bridge.remember('AI');await x.bridge.receive({id:'native-approval',method:'item/commandExecution/requestApproval',params:{threadId:'AI'}});await x.bridge.events;assert.equal(x.out[0].id,'native-approval');await x.bridge.input({id:'native-approval',result:{decision:'decline'}});assert.deepEqual(x.captured.wire.sent.at(-1),{id:'native-approval',result:{decision:'decline'}});await x.bridge.receive({method:'item/agentMessage/delta',params:{threadId:'SECONDARY',delta:'private'}});await x.bridge.events;assert.equal(x.out.length,1);}finally{x.cleanup()}});
test('disconnect reports uncertain result and never replays writes',async()=>{const x=await setup();try{x.bridge.remember('AI');await x.bridge.input({id:9,method:'turn/start',params:{threadId:'AI',input:[{type:'text',text:'QA'}]}});const before=x.captured.wire.sent.length;x.bridge.fatal('disconnect');await flush();assert.equal(x.captured.wire.sent.length,before);assert.match(x.out.at(-1).error.message,/unknown/);}finally{x.cleanup()}});
test('bridge-owned thread IDs persist across connections in same workspace',async()=>{const x=await setup();try{x.bridge.remember('AI');x.bridge.owned.clear();assert(x.bridge.owns('AI'));assert(!x.bridge.owns('SECONDARY'));}finally{x.cleanup()}});
test('native CLI thread on the same live host can attach without a fabricated manifest grant',async()=>{const x=await setup();try{x.captured.wire.loaded=['AI'];await x.bridge.input({id:31,method:'thread/resume',params:{threadId:'AI'}});assert(x.captured.wire.sent.some(m=>m.id===31&&m.method==='thread/resume'));assert(!x.bridge.owns('AI'));assert.equal(x.out.length,0);}finally{x.cleanup()}});
test('loaded state never bypasses workspace validation or survives removal from host',async()=>{const x=await setup();try{x.captured.wire.loaded=['AI','SECONDARY'];await x.bridge.input({id:32,method:'thread/resume',params:{threadId:'SECONDARY'}});assert.equal(x.out.at(-1).error.code,-32003);assert(!x.captured.wire.sent.some(m=>m.id===32));assert(await x.bridge.controls('AI'));x.captured.wire.loaded=[];assert.equal(await x.bridge.controls('AI'),false);}finally{x.cleanup()}});
test('same-host CLI approvals are forwarded, retaining the native approval id',async()=>{const x=await setup();try{x.captured.wire.loaded=['AI'];await x.bridge.receive({id:'cli-approval',method:'item/commandExecution/requestApproval',params:{threadId:'AI'}});await x.bridge.events;assert.equal(x.out.at(-1).id,'cli-approval');assert(!x.bridge.owns('AI'));}finally{x.cleanup()}});
test('start preserves native caller config while retaining authorized reasoning default',async()=>{const x=await setup();try{await x.bridge.input({id:40,method:'thread/start',params:{config:{features:{code_mode_host:true},model_reasoning_effort:'low'}}});const sent=x.captured.wire.sent.find(m=>m.id===40);assert.equal(sent.params.config.model_reasoning_effort,'high');assert.equal(sent.params.config.features.code_mode_host,true);}finally{x.cleanup()}});
