import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(process.env.DSH_MAINTENANCE_SOURCE||new URL('../public/native-local-cache.js',import.meta.url),'utf8');
if(process.env.DSH_MAINTENANCE_SCOPE)assert.equal((await readFile(process.env.DSH_MAINTENANCE_SCOPE,'utf8')).split(source.trim()).length-1,1);
const start=source.indexOf(' let lastCatalogPoll=0;'),end=source.indexOf(' const evictTimer=',start);assert(start>=0&&end>start);
function fixture({online=true,visible=true}={}){
 const windowEvents=new EventTarget(),documentEvents=new EventTarget(),timers=new Map();let now=1000000,id=0,reads=0,foreground=0,connections=0,invalidations=0;
 const document={visibilityState:visible?'visible':'hidden',addEventListener:documentEvents.addEventListener.bind(documentEvents),dispatchEvent:documentEvents.dispatchEvent.bind(documentEvents)};
 const navigator={onLine:online},knownRunning=new Set(),context={document,navigator,knownRunning,androidReader:true,eventsSocket:null,diagnostics:{catalogPollSkipped:0},Date:{now:()=>now},setTimeout(fn,ms){timers.set(++id,{fn,ms});return id},clearTimeout:id=>timers.delete(id),addEventListener:windowEvents.addEventListener.bind(windowEvents),invalidateReadChecks:()=>invalidations++,stableIpcChecked:new Map(),syncCatalog:async()=>reads++,connectEvents:async()=>connections++,refreshForeground:()=>foreground++};
 vm.runInNewContext(source.slice(start,end)+'\nglobalThis.closeMaintenance=()=>{maintenanceClosed=true;armSync()};',context);
 return {document,navigator,timers,knownRunning,event:type=>windowEvents.dispatchEvent(new Event(type)),tick(){const current=[...timers];timers.clear();for(const[,t]of current){now+=t.ms;t.fn()}},close:context.closeMaintenance,get reads(){return reads},get foreground(){return foreground},get connections(){return connections},get invalidations(){return invalidations}};
}
test('offline maintenance stops periodic catalogue attempts and resumes immediately online',()=>{const f=fixture({online:false});assert.equal(f.timers.size,0);for(let i=0;i<20;i++)f.tick();assert.equal(f.reads,0);f.navigator.onLine=true;f.event('online');assert.equal(f.reads,1);assert.equal(f.timers.size,1);f.navigator.onLine=false;f.event('offline');assert.equal(f.timers.size,0);f.event('focus');assert.equal(f.reads,1)});
test('hidden lifecycle events cannot start optional catalogue or connection work',()=>{const f=fixture({visible:false});for(const type of ['focus','pageshow','dsh:session-ready'])f.event(type);assert.equal(f.reads,0);assert.equal(f.connections,0);assert.equal(f.invalidations,0);assert.equal(f.timers.size,0);f.document.visibilityState='visible';f.document.dispatchEvent(new Event('visibilitychange'));assert.equal(f.reads,1);assert.equal(f.connections,1);assert.equal(f.timers.size,1)});
test('online foreground cadence and running-session checks retain their existing timing',()=>{const f=fixture();assert.equal([...f.timers.values()][0].ms,30000);f.tick();assert.equal(f.foreground,1);f.knownRunning.add('active');f.tick();assert.equal([...f.timers.values()][0].ms,10000);f.close();assert.equal(f.timers.size,0);f.event('online');f.event('focus');assert.equal(f.timers.size,0);const n=f.reads;f.tick();assert.equal(f.reads,n)});
