import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {mkdtemp,writeFile,rm,stat} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {serveFileResponse,byteRange} from '../src/file-response.mjs';import {fileEtag} from '../src/official-files.mjs';
test('file byte ranges reject invalid or multipart requests',()=>{assert.deepEqual(byteRange('bytes=2-5',10),{start:2,end:5});assert.deepEqual(byteRange('bytes=-3',10),{start:7,end:9});assert.equal(byteRange('bytes=12-',10),false);assert.equal(byteRange('bytes=1-2,4-5',10),false);assert.equal(byteRange('bytes=-0',10),false);});
test('file responses stream compressed content, ranges and conditional reads; changed versions refuse reuse',async t=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'betterCodex-file-response-')),file=path.join(dir,'test.txt'),text='0123456789'.repeat(1000);await writeFile(file,text);const entry={target:file,version:fileEtag(await stat(file)),expiresAt:Date.now()+600000},files={resolve:async()=>file};
 const server=http.createServer((req,res)=>serveFileResponse({files,scope:'ai',entry,req,res}).catch(e=>{res.writeHead(e.code||500);res.end();}));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});});const base='http://127.0.0.1:'+server.address().port;
 const response=await fetch(base,{headers:{'accept-encoding':'gzip'}});assert.equal(await response.text(),text);assert.equal(response.headers.get('content-encoding'),'gzip');assert.match(response.headers.get('cache-control'),/private.*immutable/);assert.equal(response.headers.get('x-betterCodex-edge-cache'),'file');
 const range=await fetch(base,{headers:{range:'bytes=12-16'}});assert.equal(range.status,206);assert.equal(await range.text(),'23456');assert.equal(range.headers.get('content-encoding'),null);
 assert.equal((await fetch(base,{headers:{'if-none-match':response.headers.get('etag')}})).status,304);await writeFile(file,'changed');assert.equal((await fetch(base)).status,409);
});
