import nodeTest from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {OfficialBoundary} from '../src/official-boundary.mjs';
import {workspace} from '../src/registry.mjs';
const R=path.dirname(fileURLToPath(import.meta.url));
const hasSdk=!!process.env.DSH_HOME_SOURCE, actualTest=nodeTest;
const test=(name,fn)=>actualTest(name,{skip:!hasSdk},fn);
const originalSdk=process.env.DSH_HOME_ORIGINAL?fs.readFileSync(process.env.DSH_HOME_ORIGINAL,'utf8'):null;
const source=process.env.DSH_HOME_OLD==='1'?originalSdk:hasSdk?fs.readFileSync(process.env.DSH_HOME_SOURCE,'utf8'):null,scopeSource=hasSdk?fs.readFileSync(process.env.DSH_HOME_SCOPE,'utf8'):null;
if(process.env.DSH_HOME_OLD==='1'&&!originalSdk)throw Error('Supply your prior generated SDK as DSH_HOME_ORIGINAL');
const A='11111111-1111-4111-a111-111111111111',MSG='22222222-2222-4222-a222-222222222222',EPOCH='33333333-3333-4333-a333-333333333333',CWD=workspace('ai').root;
function cut(s,a,b){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i,a);return s.slice(i,j);}
function fixture({personality='friendly',allowProjection=true,configError=null,scope='ai',host='local',override=false}={}){
 const calls=[],nativeCalls=[],identity={scope,frontEpoch:EPOCH,nativeGeneration:7,transportGeneration:3,connectionId:'44444444-4444-4444-a444-444444444444',resumeId:'fixture-page-resume'},settings={readExperimentPersonality:async()=>{calls.push('experiment');return 'friendly';}};let current=true,selectedHead=null,allowFast=true,pending=null,projectless=null,hostId=host,sequence=0;
 const fullConfig={model:'fixture-model',model_reasoning_effort:'ultra',service_tier:'priority',sandbox_mode:'danger-full-access',approval_policy:'never',approvals_reviewer:'user',personality,features:{safe_fixture:{nested:[1,true,'value']}},web_search:'cached'};
 const native={generation:7,on(){},start:async()=>{},rpc:async(method,params)=>{nativeCalls.push({method,params});if(method==='config/read'){if(configError)throw configError;return{config:structuredClone(fullConfig),layers:[]};}throw Error('No Native write allowed');}};
 const boundary=new OfficialBoundary({native,journal:{},configProjectionIdentity:allowProjection?s=>({scope:s,frontEpoch:EPOCH,nativeGeneration:native.generation}):null});
 const conversation={cwd:CWD,mode:'default',workspaceKind:'project',latestCollaborationMode:{mode:'default',settings:{model:'fixture-model',reasoning_effort:'high'}},latestModel:'fixture-model',latestReasoningEffort:'high',latestThreadSettings:{serviceTier:'priority'},currentPermissions:{approvalPolicy:'never',approvalsReviewer:'user',sandboxPolicy:{type:'dangerFullAccess'}}};
 const requests={hostId:host,requestPromises:new Map(),sendRequest:async(method,params,options)=>{calls.push({method,params,options});if(method==='config/read'){const id='read-fixture-'+(++sequence),reply=await boundary.call(scope,{id,method,params});return new Promise(resolve=>{const rpc={hostId:host,requestPromises:new Map([[id,{method,queuedAtMs:Date.now(),resolve}]]),clearRequestTimeout(){},releaseRequestCapacity(){},emitRequestLifecycleEvent(){}};ctx.realOnResponse.call(rpc,id,JSON.parse(JSON.stringify(reply)));});}if(method==='thread/read')return{thread:{id:A,status:{type:'idle',activeFlags:[]},threadSource:'user'}};if(method==='configRequirements/read')return{requirements:{featureRequirements:{fast_mode:allowFast}}};throw Error('No protocol write allowed');}};
 let ctx;
 const manager={disposed:false,requestClient:requests,sendRequest:requests.sendRequest,settings,logger:{info(){},warning(){}},getHostId:()=>hostId,getConversation:()=>conversation,dshSubmissionHead:()=>selectedHead,getThreadWorkspaceState:()=>pending,getThreadWritableRoots:async()=>[],readDefaultPersonality:cwd=>ctx.zan(requests,settings,cwd),getDefaultFeatureOverride:()=>false,getCodexHome:async()=>'/fixture/home',ensureDirectory:async()=>{calls.push('directory');},onNotification(){},updateTurnState(){}};
 const window={__DSH_EXECUTION_CONNECTED__:true,__DSH_EXECUTION_CONFIG_IDENTITY__:()=>({...identity})};
 ctx={console,structuredClone,AbortController,Set,Map,WeakMap,WeakSet,Object,client:manager,nativeClient:manager,window,navigator:{onLine:true},scope:{id:scope},executionEpoch:new Map(),userStopIntents:new Map(),submissionGeneration:0,hostPathEpoch:EPOCH,remoteServices:{},submissionReads:new Set(),ED:Symbol('ED'),Nv:()=>false,Gls:{kind:'available'},qI:Symbol(),BI:Symbol(),DE:Symbol(),MMs:()=>false,sO:async()=> 'send-now',Bv:{followUpQueueMode:Symbol()},globalThis:null,waitForExecution:async()=>{},executionRead:requests.sendRequest,stoppingError:()=>Error('isolated stop'),
 kI:{},nE:'local',X_:x=>x!=='local',DMs:()=>false,kMs:()=>false,Vls:async()=>{},mYn:()=>[],aMs:()=>({input:{type:'text',text:'isolated fixture input'},responseItems:[]}),uMs:()=>[],PYn:()=>[],hAt:()=>false,IA:x=>x,Ig:()=>({approvalPolicy:'never',approvalsReviewer:'user',sandboxPolicy:{type:'dangerFullAccess'}}),Ng:x=>({sandboxPolicy:x.sandboxPolicy}),OMs:()=>false,iK:()=>null,Zx:10000,
 T:{debug(){},error(){}},kX(){},mCn:()=>({}),dan:{safeParse:value=>({success:value!=null&&typeof value==='object'&&!Array.isArray(value),data:value})},Sv:undefined,Vsn:()=>({applied:null,pendingRevision:pending?.pendingRevision,workspace:pending?.workspace??null}),Wsn:()=>[],Zsn:async()=>[],Gsn:async()=>!!projectless,ecn:async()=>projectless,Ksn:({currentWorkspaceKind,hasProjectlessWorkspace})=>hasProjectlessWorkspace?'projectless':currentWorkspaceKind,DS:()=>null,Pg:()=>({approvalPolicy:'never',sandboxPolicy:{type:'dangerFullAccess'}}),Fsn:x=>x,Hsn:x=>x,RC:(a,b)=>[...new Set([...a,...b])],Lsn:(_cwd,x)=>x,Isn:()=>false,Usn:()=>[],tcn:'explicitRequestOnly',GIn:'explicitRequestOnly',Xsn:()=>null,Qsn:x=>x,Ysn:()=>null};
 delete ctx.globalThis;vm.createContext(ctx);vm.runInContext('globalThis.realOnResponse=function'+cut(source,'onResult(e,t,n){','onError(e,t,n){').slice('onResult'.length)+';'+cut(source,'function FC(','function lan(')+cut(source,'function uan(','var dan,fan=')+cut(source,'function Qjt(','var Cv=')+cut(source,'async function zan(','var Van=')+cut(source,'async function KPi(','var WW=')+cut(source,'const dshAttemptConfigs=new WeakMap();','async function EMs(')+cut(source,'function aan(','var can=')+cut(source,'async function jan(','var Man=')+cut(source,'async function Jsn(','function Ysn(')+cut(source,'async function Vls(','async function Uls(')+cut(source,'function CMs(','const dshAttemptConfigs=')+cut(source,source.includes('const dshHomeQueryAttempts=')?'const dshHomeQueryAttempts=':'function IMs(','var LMs=')+cut(scopeSource,'client.dshReadExecutionHead=async id=>{','// Read-only quota facade'),ctx);
 const entryScope={get:()=>null};
 const prepare=async({freshHead=true,messageId=MSG,cwd=CWD}={})=>{if(freshHead)selectedHead=await manager.dshReadExecutionHead(A);const context={workspaceRoots:[cwd],imageAttachments:[],fileAttachments:[],pastedTextAttachments:[],addedFiles:[]};return ctx.TMs({scope:entryScope,manager,hostId,context,targetConversationId:A,cwd,agentMode:'auto',serviceTier:'priority',shouldSendPermissionOverrides:override,activeCollaborationMode:conversation.latestCollaborationMode,restoreMessage:{id:messageId,cwd,context},clientUserMessageId:messageId});};
 const consume=(operation,id=MSG)=>ctx.Jsn(manager,A,operation.start,id,null,conversation,{canUseProjectlessWorkspace:true,canMaterializeCodexHomeRoots:true,getAdditionalWritableRoots:()=>[],isSamePath:(a,b)=>a===b,getRequestCollaborationMode:x=>x,getRequestModel:x=>x,shouldShowModelChange:()=>false});
 return{calls,nativeCalls,fullConfig,conversation,manager,settings,ctx,identity,native,boundary,prepare,consume,head:()=>selectedHead,retire:()=>{current=false;ctx.submissionGeneration++;},replaceHead:()=>{selectedHead={...selectedHead};},changeHost:()=>{hostId='remote:fixture';requests.hostId=hostId;},allowFast:x=>{allowFast=x;},pending:x=>{pending=x;},projectless:x=>{projectless=x;}};
}

function installActualQueue(f){
 const queue=fs.readFileSync(process.env.DSH_HOME_OLD==='1'?process.env.DSH_HOME_QUEUE_ORIGINAL:process.env.DSH_HOME_QUEUE,'utf8');
 delete f.manager.dshSubmissionHead;assert.equal(f.manager.dshSubmissionHead,undefined);
 const {manager,ctx}=f;manager.hostId='local';manager.inFlightConversationResumes=new Map();manager.pendingThreadSettingsUpdates=new Map();manager.addNotificationCallback=()=>{};manager.getStreamRole=()=>({role:'owner'});manager.needsResume=()=>false;manager.waitForPendingThreadSettingsUpdate=async()=>{};manager.resumeConversation=async()=>({status:'ready'});manager.settings={...manager.settings};
 f.conversation.id=A;f.conversation.resumeState='resumed';f.conversation.turns=[];
 const sent=[];manager.startTurn=async(id,operation)=>{sent.push({id,head:manager.dshSubmissionHead(id)});sent.at(-1).resolved=await f.consume({start:operation},operation.request.clientUserMessageId);return{turn:{id:'55555555-5555-4555-a555-555555555555'}};};manager.steerTurn=async()=>({turnId:'55555555-5555-4555-a555-555555555555'});
 Object.assign(ctx,{zx:class{},Ddn:[],ES:c=>c.turns.at(-1),wS:c=>c.turns,jS:c=>c.turns.at(-1),fun:()=>false,pun:()=>false,fv:()=>false,Edn(){},Adn:()=>false,Ybr:Symbol(),crypto:globalThis.crypto,location:{pathname:'/local/'+A},document:{visibilityState:'hidden',addEventListener(){}},URL,URLSearchParams,Response,CustomEvent,setTimeout,clearTimeout,setInterval:()=>1,clearInterval(){},addEventListener(){},removeEventListener(){},fetch:async()=>new Response(JSON.stringify({authority:'mac-native',state:{[A]:[]},revisions:{[A]:'fixture-revision'}}))});
 ctx.window.__DSH_SCOPE__={id:'ai',token:'fixture'};ctx.window.__DSH_NATIVE_ONLINE__=true;ctx.window.__DSH_NATIVE_CACHE__={meta:async()=>null,saveMeta:async()=>{},pendingCommands:async()=>[],recordCommand:async()=>{}};ctx.window.dispatchEvent=()=>{};
 vm.runInContext(cut(source,'async function EMs(','function DMs(')+';const Odn='+cut(source,'Odn=class extends zx{','}));function Adn(').slice(4)+';'+cut(source,'function Mdn(','var Ndn=')+';globalThis.coordinatorFactory=Mdn;',ctx);
 const q=ctx.coordinatorFactory(manager,{logger:manager.logger,storage:{readQueuedFollowUps:()=>({isLoading:false,value:{}})}},()=>{});manager.turnCoordinator=q;
 const preparation=ctx.IMs(f.uiScope,manager);q.setMessagePreparation(preparation.prepare,preparation.getQueueMode);
 vm.runInContext(queue,ctx);ctx.window.__DSH_INSTALL_NATIVE_QUEUE__(manager);assert.equal(typeof manager.dshSubmissionHead,'function');assert.equal(manager.dshSubmissionHead(A),undefined);
 const send=id=>q.sendMessage({conversationId:A,options:{executionHostId:'local',agentMode:'auto',permissionProfileId:null,serviceTier:'priority',shouldSendPermissionOverrides:false,usePermissionSelection:false,collaborationMode:null,clientUserMessageId:id},message:{id,text:'isolated fixture',cwd:CWD,context:{prompt:'isolated fixture',workspaceRoots:[CWD],imageAttachments:[],fileAttachments:[],pastedTextAttachments:[],addedFiles:[]}}});return{q,sent,send};
}

const reads=f=>f.calls.filter(x=>x?.method==='config/read');
const gate=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});promise.catch(()=>{});return{promise,resolve,reject};};
const flush=async()=>{for(let i=0;i<12;i++)await new Promise(r=>setImmediate(r));};
function homeFlow({homeError=null,headError=null,manualGate=false,active=false,queueMode=null}={}){
 const f=fixture(),home=gate(),head=gate(),events=[],queryCalls=[];let homeCalls=0,headCalls=0,queryPromise=null;
 f.uiScope={get:()=>null,query:{getOrFetch:(atom,params)=>{assert.equal(atom,f.ctx.ED);assert.equal(params.hostId,'local');queryCalls.push({atom,params});if(queryPromise)return queryPromise;homeCalls++;events.push('home-start');queryPromise=home.promise.then(value=>{events.push('home-end');return value;});return queryPromise;}}};
 const identity=()=>({...f.identity});f.ctx.__DSH_EXECUTION_CONFIG_IDENTITY__=identity;
 const originalRead=f.manager.dshReadExecutionHead;f.manager.dshReadExecutionHead=async id=>{headCalls++;events.push('head-start');await head.promise;if(headError)throw headError;const value=await originalRead(id);events.push('head-end');return value;};
 const flow=installActualQueue(f);if(active)f.conversation.threadRuntimeStatus={type:'active'};
 const send=()=>flow.send(MSG);return{f,flow,send,events,queryCalls,home,head,get homeCalls(){return homeCalls;},get headCalls(){return headCalls;},finishHome(){homeError?home.reject(homeError):home.resolve({codexHome:'/fixture/codex-home',worktreesSegment:'worktrees'});},finishHead(){head.resolve();}};
}
test('actual IMs warm callback starts exact ED query with Native head and original Hls consumes it once',async()=>{const g=homeFlow(),sending=g.send();await flush();try{assert.equal(g.homeCalls,1,'original serial path has not started home until after head');assert.equal(g.headCalls,1);assert.deepEqual(g.events.slice(0,2).sort(),['head-start','home-start']);g.finishHome();await flush();assert.equal(g.flow.sent.length,0,'no send before current head');g.finishHead();assert.equal((await sending).status,'sent');assert.equal(g.homeCalls,1);assert.equal(g.queryCalls.length,1,'Hls consumed original ED work, without another getOrFetch');assert.equal(g.headCalls,1);assert.equal(reads(g.f).length,1);assert.equal(g.flow.sent[0].resolved.request.serviceTier,'priority');}finally{g.finishHome();g.finishHead();await Promise.allSettled([sending]);}});
test('prestarted failure joins at original Vls error node, keeps object identity and performs no second query',async()=>{const error=Error('isolated exact home failure'),g=homeFlow({homeError:error}),sending=g.send();sending.catch(()=>{});await flush();g.finishHome();await flush();assert.equal(g.flow.sent.length,0);g.finishHead();await assert.rejects(sending,e=>e===error);assert.equal(g.homeCalls,1);assert.equal(g.queryCalls.length,1);assert.equal(g.flow.sent.length,0);});
test('head failure keeps its original precedence; home failure cannot reject earlier preflight',async()=>{const head=Error('isolated head failure'),home=Error('isolated home failure'),g=homeFlow({homeError:home,headError:head}),sending=g.send();sending.catch(()=>{});await flush();g.finishHome();g.finishHead();await assert.rejects(sending,e=>e===head);assert.equal(g.flow.sent.length,0);});
test('already pending ED query is coalesced, not started a second time',async()=>{const g=homeFlow();g.f.uiScope.query.getOrFetch(g.f.ctx.ED,{hostId:'local'});const sending=g.send();await flush();g.finishHome();g.finishHead();assert.equal((await sending).status,'sent');assert.equal(g.homeCalls,1);assert.equal(g.queryCalls.length,2,'existing SDK query plus warm caller; producer request only once');});
test('active UI hint avoids speculative read until original Hls entry',async()=>{const g=homeFlow({active:true}),sending=g.send();await flush();assert.equal(g.homeCalls,0);g.finishHead();await flush();assert.equal(g.homeCalls,1);g.finishHome();assert.equal((await sending).status,'sent');assert.equal(g.headCalls,1);});
test('missing negotiated identity retains original query path with no speculative read',async()=>{const g=homeFlow();g.f.ctx.__DSH_EXECUTION_CONFIG_IDENTITY__=()=>null;g.f.ctx.window.__DSH_EXECUTION_CONFIG_IDENTITY__=()=>null;const sending=g.send();await flush();assert.equal(g.homeCalls,0);g.finishHead();await flush();assert.equal(g.homeCalls,1);g.finishHome();assert.equal((await sending).status,'sent');assert.equal(g.headCalls,1);});
test('identity replacement before Hls cannot reuse the warm attempt capability',async()=>{const g=homeFlow(),sending=g.send();await flush();g.finishHome();g.f.identity.nativeGeneration++;g.finishHead();assert.equal((await sending).status,'sent');assert.equal(g.queryCalls.length,2,'fallback calls original query facade');assert.equal(g.headCalls,1);});
test('another message object cannot consume a warm capability',async()=>{const g=homeFlow(),entry={conversationId:A,message:{id:MSG,context:{}},options:{executionHostId:'local'}},preparation=g.f.ctx.IMs(g.f.uiScope,g.f.manager),release=preparation.prepare.dshWarmCodexHomeQuery(entry);await flush();g.finishHome();const take=g.f.ctx.dshTakeCodexHomeQuery(g.f.uiScope,g.f.manager,{...entry.message},A,'local',MSG);assert.equal(take,null);release();const empty=g.f.ctx.dshTakeCodexHomeQuery(g.f.uiScope,g.f.manager,entry.message,A,'local',MSG);assert.equal(empty,null);});
test('managed worktree inspection remains original and can reject restore, never granting a workspace',async()=>{const g=homeFlow(),normal=g.f.uiScope.query.getOrFetch;g.f.ctx.Nv=()=>true;g.f.ctx.J_=x=>x;g.f.ctx.jD=Symbol('jD');g.f.ctx.Xls=Symbol('Xls');g.f.ctx.qls='fixture worktree restore required';g.f.ctx.Yls='fixture worktree unavailable';let inspected=0;g.f.uiScope.query.getOrFetch=(atom,p)=>atom===g.f.ctx.jD?Promise.resolve({}):normal(atom,p);g.f.uiScope.query.invalidate=async()=>{};g.f.uiScope.query.fetch=async()=>{inspected++;return{kind:'restorable'};};const sending=g.send();sending.catch(()=>{});await flush();g.finishHome();g.finishHead();await assert.rejects(sending,/worktree restore/);assert.equal(inspected,1);assert.equal(g.flow.sent.length,0);assert.equal(g.homeCalls,1);});
test('virtual injected 1.4s head and 1.6s original home show serial versus parallel wall time',async()=>{const g=homeFlow(),sending=g.send();let settled=false,outcome=null;sending.then(value=>{settled=true;outcome=value},error=>{settled=true;outcome=error});let now=0,headAt=null,homeAt=null,headDone=false,homeDone=false;for(let round=0;round<8&&!settled;round++){await flush();if(g.headCalls&&!headDone&&headAt==null)headAt=now+1400;if(g.homeCalls&&!homeDone&&homeAt==null)homeAt=now+1600;const ready=[!headDone&&headAt,!homeDone&&homeAt].filter(x=>x!==false&&x!=null);assert(ready.length,'fixture must have a pending original producer');now=Math.min(...ready);if(!headDone&&headAt===now){headDone=true;g.finishHead();}if(!homeDone&&homeAt===now){homeDone=true;g.finishHome();}await flush();}assert.equal(outcome?.status,'sent');assert.equal(g.homeCalls,1);assert.equal(g.headCalls,1);const old=process.env.DSH_HOME_OLD==='1';assert.equal(now,old?3000:1600);if(process.env.DSH_HOME_TIMING_OUTPUT)fs.writeFileSync(process.env.DSH_HOME_TIMING_OUTPUT,JSON.stringify({producerDelaysInjected:true,actualInstallerAndSdkCaller:true,headDelayMs:1400,homeDelayMs:1600,wallMs:now,homeProducerCalls:g.homeCalls,nativeHeadReads:g.headCalls,notNaturalPhoneTiming:true},null,2)+'\n');});
