import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {endToEndHeaders} from '../src/http-headers.mjs';import {createOfficialPreviewProxy} from '../src/official-preview-proxy.mjs';
test('hop headers never strip end-to-end credentials or content metadata',()=>{assert.deepEqual(endToEndHeaders({connection:'keep-alive, x-private-hop','keep-alive':'timeout=5','transfer-encoding':'chunked','x-private-hop':'value','content-type':'text/javascript',authorization:'Bearer value','x-betterCodex-scope':'scoped'}),{'content-type':'text/javascript',authorization:'Bearer value','x-betterCodex-scope':'scoped'});});
test('HTML followed by scripts stays valid across close and persistent downstream connections',async t=>{
 const upstream=http.createServer((req,res)=>{res.setHeader('connection','keep-alive');res.setHeader('keep-alive','timeout=5');res.setHeader('transfer-encoding','chunked');res.end(req.url==='/page'?'<!doctype html><head></head><body>page</body>':'const loaded=true;');});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));
 const proxy=createOfficialPreviewProxy({upstream:'http://127.0.0.1:'+upstream.address().port}),server=http.createServer((req,res)=>proxy.route(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 t.after(async()=>{server.closeAllConnections();upstream.closeAllConnections();await Promise.all([new Promise(r=>server.close(r)),new Promise(r=>upstream.close(r))]);});
 const get=(path,connection)=>new Promise((resolve,reject)=>{http.get({hostname:'127.0.0.1',port:server.address().port,path,headers:{connection}},r=>{let body='';r.on('data',b=>body+=b);r.on('end',()=>resolve({status:r.statusCode,body}));}).on('error',reject)});
 for(const connection of ['close','keep-alive'])for(let i=0;i<3;i++){assert.equal((await get('/page',connection)).status,200);const js=await get('/scope.js',connection);assert.equal(js.status,200);assert.equal(js.body,'const loaded=true;');}
});
