import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {randomUUID}from'node:crypto';import {mkdtemp,rm}from'node:fs/promises';import os from'node:os';import path from'node:path';
import {Hub}from'../src/hub.mjs';import {Journal}from'../src/journal.mjs';import {Attachments}from'../src/attachments.mjs';import {WORKSPACES,fail}from'../src/registry.mjs';
async function setup(t){const dir=await mkdtemp(path.join(os.tmpdir(),'native-web-test-')),journal=new Journal(dir),threads=new Map(),hosts=[];
 class Fake extends EventEmitter{state='ready';calls=[];sent=[];async start(){return this;}async close(){}send(m){this.sent.push(m);}async rpc(method,p){this.calls.push({method,p});if(method==='thread/start'){const thread={id:randomUUID(),cwd:p.cwd,status:{type:'idle'},historyMode:'paginated',turns:[]};threads.set(thread.id,thread);return{thread};}if(method==='thread/list')return{data:[...threads.values()],nextCursor:null};const thread=threads.get(p.threadId);if(!thread)throw fail(502,'not found');if(method==='thread/read'){if(this.persistencePending)throw fail(502,'not found yet');return{thread};}if(method==='thread/turns/list'){if(this.persistencePending)throw fail(502,'list_turns is not supported yet');return{data:thread.turns,nextCursor:null};}if(method==='thread/resume'){thread.status={type:'idle'};return{thread};}if(method==='turn/start'){if(this.dropAck)throw fail(504,'ACK lost');const turn={id:randomUUID(),status:'inProgress',items:[]};thread.turns.push(turn);return{turn};}if(method==='turn/interrupt')return{};if(method==='thread/items/list')return{data:[],nextCursor:null};throw new Error(method);}}
 const nativeFactory=()=>{const h=new Fake();hosts.push(h);return h;};const hub=new Hub({journal,nativeFactory}),attachments=new Attachments(path.join(dir,'attachments'));
 t.after(async()=>{await hub.close();journal.close();await rm(dir,{recursive:true,force:true});});return{hub,journal,threads,hosts,attachments,nativeFactory,dir};}
async function create(s,ws){const r=await s.hub.mutate(ws,{op:'new',requestId:randomUUID()},s.attachments);assert.equal(r.state,'accepted');return r.result.thread.id;}

test('ai/secondary native directory filters and direct guessed IDs enforce server ownership of scope',async t=>{const s=await setup(t),a=await create(s,WORKSPACES.ai),z=await create(s,WORKSPACES.secondary);assert.deepEqual((await s.hub.list(WORKSPACES.ai)).data.map(x=>x.id),[a]);assert.deepEqual((await s.hub.list(WORKSPACES.secondary)).data.map(x=>x.id),[z]);for(const op of ['send','stop','approval'])await assert.rejects(s.hub.mutate(WORKSPACES.ai,{op,threadId:z,requestId:randomUUID(),text:'bad'},s.attachments),{code:404});await assert.rejects(s.hub.snapshot(WORKSPACES.secondary,a),{code:404});await assert.rejects(s.hub.items(WORKSPACES.ai,z,'turn'),{code:404});});

test('new-thread persistence window uses only same-host native metadata and live items',async t=>{const s=await setup(t),id=await create(s,WORKSPACES.ai),h=s.hosts[0],turnId=randomUUID();h.persistencePending=true;await s.hub.nativeEvent(WORKSPACES.ai,{method:'turn/started',params:{threadId:id,turn:{id:turnId,status:'inProgress',items:[]}}},false);await s.hub.nativeEvent(WORKSPACES.ai,{method:'item/started',params:{threadId:id,turnId,item:{id:'msg',type:'agentMessage',text:''}}},false);await s.hub.nativeEvent(WORKSPACES.ai,{method:'item/agentMessage/delta',params:{threadId:id,turnId,itemId:'msg',delta:'native delta'}},false);const snap=await s.hub.snapshot(WORKSPACES.ai,id);assert.equal(snap.turns[0].items[0].text,'native delta');await assert.rejects(s.hub.snapshot(WORKSPACES.secondary,id),{code:404});});

test('concurrent identical writes execute once and request ID reuse with changed body is rejected',async t=>{const s=await setup(t),id=await create(s,WORKSPACES.ai),b={op:'send',threadId:id,requestId:randomUUID(),text:'once'};const rs=await Promise.all([s.hub.mutate(WORKSPACES.ai,b,s.attachments),s.hub.mutate(WORKSPACES.ai,b,s.attachments)]);assert.equal(rs[0].result.turn.id,rs[1].result.turn.id);assert.equal(s.hosts[0].calls.filter(x=>x.method==='turn/start').length,1);await assert.rejects(s.hub.mutate(WORKSPACES.ai,{...b,text:'changed'},s.attachments),{code:409});});

test('lost ACK remains unknown and never repeats the native side effect',async t=>{const s=await setup(t),id=await create(s,WORKSPACES.ai);s.hosts[0].dropAck=true;const b={op:'send',threadId:id,requestId:randomUUID(),text:'once'};assert.equal((await s.hub.mutate(WORKSPACES.ai,b,s.attachments)).state,'unknown');assert.equal((await s.hub.mutate(WORKSPACES.ai,b,s.attachments)).state,'unknown');assert.equal(s.hosts[0].calls.filter(x=>x.method==='turn/start').length,1);});

test('durable managed ownership permits same gateway recovery but reads/reconnect do not resume',async t=>{const s=await setup(t),id=await create(s,WORKSPACES.ai);await s.hub.close();const next=new Hub({journal:s.journal,nativeFactory:s.nativeFactory});await next.snapshot(WORKSPACES.ai,id);await next.list(WORKSPACES.ai);assert.equal(s.hosts[1].calls.some(x=>x.method==='thread/resume'||x.method==='turn/start'),false);const r=await next.mutate(WORKSPACES.ai,{op:'send',threadId:id,requestId:randomUUID(),text:'explicit continuation'},s.attachments);assert.equal(r.state,'accepted');assert.equal(s.hosts[1].calls.filter(x=>x.method==='thread/resume').length,1);await next.close();});

test('two clients can resolve one approval only once; resolution and stop stay thread scoped',async t=>{const s=await setup(t),id=await create(s,WORKSPACES.ai),z=await create(s,WORKSPACES.secondary);const request={id:7,method:'item/commandExecution/requestApproval',params:{threadId:id,turnId:'turn',itemId:'command',command:'echo QA',availableDecisions:['accept','decline','cancel']}};await s.hub.nativeEvent(WORKSPACES.ai,request,true);const key=[...s.hub.approvals.keys()][0],b={op:'approval',threadId:id,approvalKey:key,decision:'accept'};const rs=await Promise.all([s.hub.mutate(WORKSPACES.ai,{...b,requestId:randomUUID()},s.attachments),s.hub.mutate(WORKSPACES.ai,{...b,requestId:randomUUID()},s.attachments)]);assert.deepEqual(rs.map(x=>x.state).sort(),['accepted','rejected']);assert.equal(s.hosts[0].sent.length,1);assert.equal((await s.hub.snapshot(WORKSPACES.secondary,z)).approvals.length,0);await s.hub.nativeEvent(WORKSPACES.ai,{method:'serverRequest/resolved',params:{requestId:7}},false);assert.equal(s.hub.approvals.size,0);s.hub.active.set(id,'turn');assert.equal((await s.hub.mutate(WORKSPACES.ai,{op:'stop',threadId:id,requestId:randomUUID()},s.attachments)).state,'accepted');assert.deepEqual(s.hosts[0].calls.at(-1).p,{threadId:id,turnId:'turn'});});

test('attachment IDs are scoped by workspace AND thread; arbitrary paths are never inputs',async t=>{const s=await setup(t),a=await create(s,WORKSPACES.ai),b=await create(s,WORKSPACES.ai);const attachment=await s.attachments.add(WORKSPACES.ai,a,{name:'qa.txt',mime:'text/plain',data:Buffer.from('QA').toString('base64')});assert.equal((await s.attachments.resolve(WORKSPACES.ai,a,[attachment.id]))[0].type,'text');await assert.rejects(s.attachments.resolve(WORKSPACES.secondary,a,[attachment.id]),{code:404});await assert.rejects(s.attachments.resolve(WORKSPACES.ai,b,[attachment.id]),{code:404});await assert.rejects(s.attachments.resolve(WORKSPACES.ai,a,['/etc/passwd']),{code:404});});

test('process interruption is explicit, removes pending approvals, never hot restarts',async t=>{const s=await setup(t),id=await create(s,WORKSPACES.ai);const seen=[];s.hub.on('event',e=>seen.push(e));s.hosts[0].state='interrupted';s.hosts[0].emit('interrupted',{reason:'fixture crash'});await assert.rejects(s.hub.host(WORKSPACES.ai),{code:503});assert.equal(s.hosts.length,1);assert.equal(s.hub.loaded.has(id),false);assert.equal(seen.at(-1).method,'host/interrupted');});

test('journal restart preserves owned threads and converts pending requests to unknown',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'native-web-journal-'));let j=new Journal(dir);const id=randomUUID(),rid=randomUUID();j.manageThread('ai',id);j.db.prepare('INSERT INTO requests VALUES(?,?,?,?,?)').run('ai',rid,'hash','pending',null);j.close();j=new Journal(dir);assert.equal(j.ownsThread('ai',id),true);assert.equal(j.ownsThread('secondary',id),false);assert.equal(j.get('ai',rid).state,'unknown');j.close();await rm(dir,{recursive:true,force:true});});
