import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=await readFile(process.env.DSH_LOADER_TEST_SOURCE||new URL('../public/native-loader.js',import.meta.url),'utf8');
const embedded=/ const release=(\{[^\n]+\}),url=new URL/.exec(source);const release=embedded?JSON.parse(embedded[1]):{scope:'/scope.js',runtime:'/runtime.js',pwa:'/pwa.js',entry:'/entry.js',shell:'/shell.html'};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
const flush=async()=>{for(let i=0;i<30;i++)await Promise.resolve()};
function boot({cached={marker:'cached'},scopeResult=true,mac=deferred(),cloud=deferred(),android=null,pwa=null,runtime=null}={}){
 const events=new EventTarget(),documentEvents=new EventTarget(),intervals=[],loaded=[],calls=[],writes=[],errors=[];
 const scope=deferred(),root={replaceChildren(){},append(){}},cache={restoreAtoms:async()=>({}),meta:async key=>key==='bootstrap'?cached:false,prepareSidebarBootstrap:async v=>v,saveMeta:async(...v)=>writes.push(v)};
 const window={__DSH_THEME_COLOR__:{},addEventListener:events.addEventListener.bind(events),dispatchEvent:events.dispatchEvent.bind(events),__DSH_NATIVE_CACHE__:cache,__DSH_CLIENT_LOG__:{reportError:(...v)=>errors.push(v)}};
 if(android)window.__DSH_ANDROID_CACHE_READY__=android.promise;
 let refreshes=0;
 const renew=async()=>{refreshes++;const ok=await scope.promise;if(ok){window.__DSH_SCOPE__.token='fixture';window.dispatchEvent(new Event('dsh:scope-renewed'))}return ok};
 window.__DSH_RENEW_SCOPE__=renew;
 window.__DSH_ACCEPT_SESSION_READY__=()=>{if(window.authBlocked)return false;window.__DSH_CONNECTION_PAUSED__=false;return true};
 window.addEventListener('dsh:authentication-required',()=>{window.authBlocked=true;window.__DSH_CONNECTION_PAUSED__=true});
 let ready=0,reconnect=0;window.addEventListener('dsh:session-ready',()=>ready++);window.__DSH_RECONNECT_TRANSPORT__=()=>reconnect++;
 window.__DSH_CONNECTION_JSON__=async url=>{calls.push(url);if(url.startsWith('/dsh-scope-session')){const ok=await scope.promise;return {response:{ok,status:ok?200:503},data:ok?{id:'ai',token:'fixture'}:null}}return url.startsWith('/sync/')?cloud.promise:mac.promise};
 const storage={getItem:()=>null,setItem(){}};
 const context={window,URL,Event,CustomEvent:class extends Event{constructor(type,init){super(type);this.detail=init?.detail}},structuredClone,Promise,MutationObserver:class{observe(){}disconnect(){}},location:new URL('https://example.test/?workspace=ai'),navigator:{onLine:true},localStorage:storage,sessionStorage:storage,matchMedia:()=>({matches:false}),crypto:{getRandomValues:a=>a.fill(1)},history:{replaceState(){}},addEventListener:window.addEventListener,setInterval:fn=>intervals.push(fn),clearInterval:id=>{intervals[id-1]=null},setTimeout,document:{visibilityState:'visible',addEventListener:documentEvents.addEventListener.bind(documentEvents),dispatchEvent:documentEvents.dispatchEvent.bind(documentEvents),documentElement:{dataset:{}},getElementById:()=>root,querySelector:()=>null,createElement:()=>({}),head:{append(e){if(e.src){loaded.push(e.src);const pending=e.src===release.pwa?pwa:e.src===release.runtime?runtime:null;if(pending)pending.promise.then(()=>e.onload(),()=>e.onerror());else queueMicrotask(()=>e.onload())}}}}};
 vm.runInNewContext(source.replace('__DSH_NATIVE_RELEASE__',JSON.stringify(release)),context);
 if(scopeResult!==null)scope.resolve(scopeResult);
 return {window,document:context.document,navigator:context.navigator,scope,mac,cloud,loaded,calls,writes,errors,intervals,tick(){for(const fn of [...intervals])fn?.()},activeTimers:()=>intervals.filter(Boolean).length,get ready(){return ready},get reconnect(){return reconnect},get refreshes(){return refreshes}};
}
test('cached renderer recovers control while optional startup snapshot never returns',async()=>{const b=boot();await flush();assert(b.loaded.includes(release.entry));assert.equal(b.window.__DSH_SCOPE__.token,'fixture');assert(b.ready>0);assert.equal(b.window.__DSH_CONNECTION_PAUSED__,false);assert(!b.calls.some(x=>x.startsWith('/sync/')));});
test('scope renewal after a failed initial request immediately resumes without bootstrap or timer',async()=>{const b=boot({scopeResult:false});await flush();assert.equal(b.ready,0);b.window.__DSH_SCOPE__.token='renewed';b.window.dispatchEvent(new Event('dsh:scope-renewed'));await flush();assert(b.ready>0);assert.equal(b.window.__DSH_CONNECTION_PAUSED__,false);assert(b.reconnect>0);});
test('late optional snapshot failure cannot pause an already connected page',async()=>{const b=boot();await flush();b.window.__DSH_EXECUTION_CONNECTED__=true;b.mac.reject(Error('optional read failed'));await flush();assert.equal(b.window.__DSH_CONNECTION_PAUSED__,false);assert.equal(b.window.__DSH_NATIVE_ONLINE__,true);assert.equal(b.errors.length,0);});
test('authentication rejection remains authoritative over a delayed valid snapshot',async()=>{const b=boot();await flush();b.window.dispatchEvent(new Event('dsh:authentication-required'));const writes=b.writes.length;b.mac.resolve({response:{ok:true},data:{marker:'fresh'}});await flush();assert.equal(b.window.__DSH_CONNECTION_PAUSED__,true);assert.equal(b.writes.length,writes);assert.equal(b.window.__DSH_NATIVE_ONLINE__,false);});
test('cold renderer uses first valid configuration without waiting for the other source',async()=>{const b=boot({cached:null});await flush();assert(!b.loaded.includes(release.entry));b.mac.resolve({response:{ok:true},data:{marker:'mac'}});await flush();assert(b.loaded.includes(release.entry));assert.equal(b.window.__CODEX_WEB_CONFIG__.marker,'mac');assert(b.ready>0);});
test('recovery timer refreshes credentials without launching another bootstrap read',async()=>{const b=boot();await flush();const count=b.calls.filter(x=>x.includes('/api/native-bootstrap')).length;b.intervals[0]();await flush();assert.equal(b.calls.filter(x=>x.includes('/api/native-bootstrap')).length,count);});
test('first online configuration is not blocked by a stalled Android delta import',async()=>{const b=boot({cached:null,android:deferred()});await flush();assert(b.calls.some(x=>x.startsWith('/sync/')),'cloud read starts beside the optional importer');b.cloud.resolve({response:{ok:true},data:{config:{marker:'cloud'}}});await flush();assert(b.loaded.includes(release.entry));assert.equal(b.window.__CODEX_WEB_CONFIG__.marker,'cloud');});
test('optional PWA chrome load cannot hold the authenticated cached renderer',async()=>{const pwa=deferred(),b=boot({pwa});await flush();assert(b.loaded.includes(release.entry));assert(b.ready>0);pwa.reject(Error('optional resource failed'));await flush();assert.equal(b.window.__DSH_NATIVE_ONLINE__,true);assert.equal(b.errors.length,0,'optional chrome failure never replaces the renderer with a boot error');});
test('mandatory runtime still completes before the renderer entry is allowed to execute',async()=>{const runtime=deferred(),b=boot({runtime});await flush();assert(!b.loaded.includes(release.entry));runtime.resolve();await flush();assert(b.loaded.includes(release.entry));});

test('hidden recovery suspends the periodic credential loop and foreground resumes immediately',async()=>{const b=boot();await flush();const initial=b.refreshes;b.document.visibilityState='hidden';b.document.dispatchEvent(new Event('visibilitychange'));assert.equal(b.activeTimers(),0);for(let i=0;i<20;i++){b.tick();await flush();}assert.equal(b.refreshes,initial);b.document.visibilityState='visible';b.document.dispatchEvent(new Event('visibilitychange'));await flush();assert.equal(b.refreshes,initial+1);assert.equal(b.activeTimers(),1);});
test('offline recovery has no periodic requests and online wakes exactly one preparation',async()=>{const b=boot();await flush();const initial=b.refreshes;b.navigator.onLine=false;b.window.dispatchEvent(new Event('offline'));assert.equal(b.activeTimers(),0);for(let i=0;i<20;i++){b.tick();await flush();}assert.equal(b.refreshes,initial);b.navigator.onLine=true;b.window.dispatchEvent(new Event('online'));b.window.dispatchEvent(new Event('focus'));await flush();assert.equal(b.refreshes,initial+1);assert.equal(b.activeTimers(),1);});
test('connected and auth-blocked recovery remove idle timers without weakening authentication',async()=>{const b=boot();await flush();b.window.__DSH_EXECUTION_CONNECTED__=true;b.window.dispatchEvent(new Event('dsh:execution-state'));assert.equal(b.activeTimers(),0);const initial=b.refreshes;b.tick();await flush();assert.equal(b.refreshes,initial);b.window.__DSH_EXECUTION_CONNECTED__=false;b.window.dispatchEvent(new Event('dsh:execution-state'));assert.equal(b.activeTimers(),1);b.window.dispatchEvent(new Event('dsh:authentication-required'));assert.equal(b.activeTimers(),0);b.window.dispatchEvent(new Event('focus'));await flush();assert.equal(b.refreshes,initial);});
test('pagehide stops periodic recovery and pageshow resumes without reloading or reading bootstrap again',async()=>{const b=boot();await flush();const reads=b.calls.filter(x=>x.includes('/api/native-bootstrap')).length;b.window.dispatchEvent(new Event('pagehide'));assert.equal(b.activeTimers(),0);b.window.dispatchEvent(new Event('pageshow'));await flush();assert.equal(b.activeTimers(),1);assert.equal(b.calls.filter(x=>x.includes('/api/native-bootstrap')).length,reads);});

test('late recovery completion cannot restart timers after pagehide',async()=>{const b=boot();await flush();const held=deferred();b.window.__DSH_RENEW_SCOPE__=()=>held.promise;b.window.dispatchEvent(new Event('focus'));b.window.dispatchEvent(new Event('pagehide'));held.resolve(true);await flush();assert.equal(b.activeTimers(),0);b.window.dispatchEvent(new Event('pageshow'));await flush();assert.equal(b.activeTimers(),1);});
