import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../public/native-local-cache.js',import.meta.url),'utf8');
const part=source.slice(source.indexOf(' const PREWARM_TURNS='),source.indexOf(" document.addEventListener('input'"));
function fixture(){const calls=[],id='00000000-0000-4000-8000-4ba7215b54d2',c={Set,Map,Date,diagnostics:{},pinnedWarmed:new Set(),get:async()=>null,meta:async()=>null,readKey:(method,params)=>JSON.stringify([method,params]),lastForeground:0,pendingReads:new Map(),navigator:{onLine:true},document:{visibilityState:'visible'},location:{pathname:'/'},window:{__BETTER_CODEX_NATIVE_ONLINE__:true,__BETTER_CODEX_NATIVE_SIDEBAR__:{isList:true}},nativeClient:null,setTimeout:()=>1,fetchRead:async(method,params,fresh,priority)=>{calls.push({method,params,fresh,priority});return {payload:{result:{data:method==='thread/turns/list'?Array.from({length:params.limit},(_,i)=>({id:'turn-'+i})):[]}}};},catalogPage:async p=>({entries:p.limit===20?Array.from({length:20},(_,i)=>({threadId:i===0?id:'22222222-2222-4222-a222-'+String(i).padStart(12,'0'),sourceUpdatedAt:10})):[]})};vm.runInNewContext(part+';globalThis.testApi={warmPinned,scanRunning,runBackground,queue:backgroundQueue};',c);return {c,calls,id};}
test('pinned prewarm prepares six turns using only low-priority read calls',async()=>{const f=fixture();await f.c.testApi.warmPinned({threadIds:[f.id]});await f.c.testApi.runBackground();assert.equal(f.calls.filter(x=>x.method==='thread/items/list').length,6);assert(f.calls.every(x=>x.priority==='low'&&x.fresh===false));assert.equal(f.c.diagnostics.background.completed,1);});
test('recent scan queues twenty recent threads and pauses deep work when foreground activity starts',async()=>{const f=fixture();await f.c.testApi.scanRunning();assert.equal(f.c.testApi.queue.size,20);const read=f.c.fetchRead;f.c.fetchRead=async(...args)=>{const result=await read(...args);if(args[0]==='thread/items/list')f.c.lastForeground=Date.now();return result;};await f.c.testApi.runBackground();assert.equal(f.calls.filter(x=>x.method==='thread/items/list').length,1);assert.equal(f.c.testApi.queue.size,20);assert.equal(f.c.diagnostics.background.completed,0);});

test('already cached prewarm pages do not repeat cloud reads',async()=>{const f=fixture();f.c.get=async key=>{const [method,params]=JSON.parse(key);return {key,revision:2,payload:{result:{data:method==='thread/turns/list'?Array.from({length:params.limit},(_,i)=>({id:'turn-'+i})):[]}}};};await f.c.testApi.warmPinned({threadIds:[f.id]});await f.c.testApi.runBackground();assert.equal(f.calls.length,0);assert.equal(f.c.diagnostics.background.completed,1);});
