import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {NativeReadCache,nativeReadKey} from '../src/native-read-cache.mjs';
import {SyncOutbox} from '../src/sync-outbox.mjs';
import {Journal} from '../src/journal.mjs';
import {randomUUID} from 'node:crypto';
const id='00000000-0000-4000-8000-4ba7215b54d2';
function fixture(t){const dir=mkdtempSync(tmpdir()+'/betterCodex-full-cache-');let calls=0;const boundary={call:async(scope,p)=>{calls++;if(scope!=='ai')throw Object.assign(Error('wrong scope'),{code:404});return {data:[{id:'item',type:'unknownFutureNativeType',opaque:{full:'keep'},text:'full output'}],nextCursor:'native-opaque-cursor'};}};let cache=new NativeReadCache(dir,{boundary});t.after(()=>{cache.close();rmSync(dir,{recursive:true,force:true});});return {dir,boundary,get cache(){return cache},get calls(){return calls},reopen(){cache.close();cache=new NativeReadCache(dir,{boundary});return cache;}};}
test('native DTO cache preserves unknown types, cursor and source identity across reopen',async t=>{const f=fixture(t),params={threadId:id,turnId:id,limit:20};const r=await f.cache.read('ai','thread/items/list',params);assert.equal(r.payload.result.data[0].opaque.full,'keep');assert.equal(r.payload.result.nextCursor,'native-opaque-cursor');const generation=r.sourceGeneration;f.reopen();const cached=await f.cache.read('ai','thread/items/list',{limit:20,turnId:id,threadId:id});assert.equal(f.calls,1);assert.equal(cached.sourceGeneration,generation);assert.equal(cached.key,nativeReadKey('thread/items/list',params));assert.equal(f.cache.get('secondary',r.key),null);});
test('failed local commit never creates a change cursor',t=>{const f=fixture(t);f.cache.db.exec("CREATE TRIGGER reject_cache BEFORE INSERT ON cache_records BEGIN SELECT RAISE(ABORT,'disk failure'); END");assert.throws(()=>f.cache.put('ai','test','history',id,{text:'not committed'}),/disk failure/);assert.equal(f.cache.changes().records.length,0);assert.equal(f.cache.db.prepare('SELECT count(*) n FROM cache_changes').get().n,0);});
test('history rewrite invalidates a cached page and an in-flight old snapshot',async t=>{const f=fixture(t),params={threadId:id,includeTurns:false};await f.cache.read('ai','thread/read',params);const old=f.cache.get('ai',nativeReadKey('thread/read',params));f.cache.invalidate('ai',id,{rewrite:true});await f.cache.read('ai','thread/read',params);assert.equal(f.calls,2);assert.notEqual(f.cache.get('ai',old.key).generation,old.generation);let release;f.boundary.call=()=>new Promise(r=>{release=r;});const pending=f.cache.read('ai','thread/read',{...params,includeTurns:true},{fresh:true});f.cache.invalidate('ai',id,{rewrite:true});release({thread:{id}});await assert.rejects(pending,e=>e.code===409);});
test('durable outbox resumes only unacknowledged frames and rejects a future ACK',t=>{const f=fixture(t);let box=new SyncOutbox(f.cache);const first=box.append({event:{type:'host',online:true}}),second=box.append({scope:'ai',threadId:id,event:{type:'status',status:{type:'active'}}});box.acknowledge(first.seq);const epoch=box.epoch;f.reopen();box=new SyncOutbox(f.cache);assert.equal(box.epoch,epoch);assert.equal(box.sequence,second.seq);assert.deepEqual(box.entries().map(e=>e.seq),[second.seq]);assert.throws(()=>box.acknowledge(second.seq+1));box.acknowledge(second.seq);assert.equal(box.entries().length,0);});
test('opening another live command ledger preserves pending ownership and one execution',async t=>{const dir=mkdtempSync(tmpdir()+'/betterCodex-shared-journal-'),a=new Journal(dir),id=randomUUID();let release,calls=0;const pending=a.run('ai',id,{op:'same'},()=>{calls++;return new Promise(r=>release=r);});const b=new Journal(dir);assert.equal(b.get('ai',id).state,'pending');const retry=await b.run('ai',id,{op:'same'},async()=>{calls++;});assert.equal(retry.state,'pending');release({accepted:true});await pending;assert.equal((await b.run('ai',id,{op:'same'},async()=>{calls++;})).result.accepted,true);assert.equal(calls,1);a.close();b.close();rmSync(dir,{recursive:true,force:true});});
test('equivalent optional cursors and capped limits reuse the same native page',async t=>{const f=fixture(t);await f.cache.read('ai','thread/turns/list',{threadId:id,cursor:null,limit:100,itemsView:null});await f.cache.read('ai','thread/turns/list',{threadId:id,limit:20,itemsView:'summary',sortDirection:'desc'});assert.equal(f.calls,1);assert.equal(nativeReadKey('thread/items/list',{threadId:id,cursor:null,limit:40}),nativeReadKey('thread/items/list',{threadId:id,sortDirection:'asc'}));});
test('completed native item head is reused across resume snapshot cursors and invalidated on rewrite',async t=>{
 const f=fixture(t),params={threadId:id,turnId:id,cursor:'old-head',limit:20,sortDirection:'desc'};f.cache.put('ai','turn:'+id+':'+id,'turn',id,{turn:{id,status:'completed'}});f.cache.rememberCursors('ai',{thread:{id},itemsBackwardsCursor:'old-head',turnsBackwardsCursor:'turn-head'});const original=await f.cache.read('ai','thread/items/list',params);f.cache.rememberCursors('ai',{thread:{id},itemsBackwardsCursor:'new-head',turnsBackwardsCursor:'turn-head'});const cached=await f.cache.read('ai','thread/items/list',{...params,cursor:'new-head'});assert.equal(f.calls,1);assert.deepEqual(cached.payload.result,original.payload.result);assert.equal(cached.key,nativeReadKey('thread/items/list',{...params,cursor:'new-head'}));f.cache.invalidate('ai',id,{rewrite:true});await f.cache.read('ai','thread/items/list',{...params,cursor:'new-head'});assert.equal(f.calls,2);
});
