import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const script=await readFile(new URL('../public/native-theme-color.js',import.meta.url),'utf8');
function setup({dark=false,hint=null,storageBlocked=false}={}){
 const classes=new Set(),root={classList:{contains:x=>classes.has(x)},dataset:{},style:{}},meta={content:'#ffffff',hasAttribute:()=>false,removeAttribute(){},matches:()=>true},listeners={},system={matches:dark,addEventListener:(k,f)=>listeners.system=f};let update,headUpdate,saved;const head={};
 const localStorage={getItem(){if(storageBlocked)throw Error('blocked');return JSON.stringify(hint)},setItem(k,v){saved=JSON.parse(v)}};
 vm.runInNewContext(script,{window:{__BETTER_CODEX_SCOPE__:{id:'ai'}},document:{head,visibilityState:'visible',addEventListener:(k,f)=>listeners[k]=f,documentElement:root,querySelector:()=>null,querySelectorAll:()=>[meta]},location:{protocol:'https:'},matchMedia:()=>system,localStorage,addEventListener:(k,f)=>listeners[k]=f,MutationObserver:class{constructor(f){this.fn=f}observe(target){if(target===root)update=this.fn;else headUpdate=this.fn}}});
 return {root,meta,system,listeners,classes,update,headUpdate,get saved(){return saved}};
}
test('system dark color is available before native render and follows later theme classes',()=>{const x=setup({dark:true});assert.equal(x.meta.content,'#000000');x.classes.add('electron-light');x.update();assert.equal(x.meta.content,'#ffffff');assert.equal(x.root.style.colorScheme,'light');x.classes.clear();x.classes.add('electron-dark');x.update();assert.equal(x.meta.content,'#000000');});
test('manual dark on a light system controls the PWA bar and persists a startup hint',()=>{const x=setup();x.classes.add('electron-dark');x.update();assert.equal(x.meta.content,'#000000');const next=setup({hint:x.saved});assert.equal(next.meta.content,'#000000');next.classes.add('electron-light');next.update();assert.equal(next.meta.content,'#ffffff');});
test('system changes invalidate a stale startup hint; unavailable storage cannot break theme updates',()=>{const x=setup({dark:false,hint:{variant:'light',systemDark:true}});assert.equal(x.meta.content,'#ffffff');x.system.matches=true;x.listeners.system();assert.equal(x.meta.content,'#000000');const y=setup({dark:true,storageBlocked:true});assert.equal(y.meta.content,'#000000');y.classes.add('electron-light');y.update();assert.equal(y.meta.content,'#ffffff');});

test('later gray or white metadata writes recover black without a theme class change',()=>{const x=setup({dark:true});for(const color of ['#ffffff','#202020']){x.meta.content=color;x.headUpdate([{type:'attributes',target:x.meta}]);assert.equal(x.meta.content,'#000000');}x.meta.content='#ffffff';x.listeners.visibilitychange();assert.equal(x.meta.content,'#000000');});
test('metadata replacement and page restoration reapply a manual dark startup preference',()=>{const x=setup({hint:{variant:'dark',systemDark:false}});x.meta.content='#ffffff';x.headUpdate([{type:'childList'}]);assert.equal(x.meta.content,'#000000');x.meta.content='#333333';x.listeners.pageshow();assert.equal(x.meta.content,'#000000');});
