import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../public/official-service-worker.js',import.meta.url),'utf8');
function boot({recipient='ai'}={}){const handlers={},shown=[],requests=[],opened=[],entries=new Map();if(recipient)entries.set('/__betterCodex-notification-recipient-v1',new Response(JSON.stringify({recipient})));const self={location:{origin:'http://localhost:3080'},addEventListener:(type,fn)=>handlers[type]=fn,registration:{showNotification:async(title,options)=>shown.push({title,options})},clients:{matchAll:async()=>[],openWindow:async url=>opened.push(url)}};vm.runInNewContext(source,{self,URL,Response,caches:{open:async()=>({match:async key=>entries.get(key)?.clone(),put:async(key,value)=>entries.set(key,value)})},fetch:async(...args)=>{requests.push(args);return{ok:true}}});return{handlers,self,shown,requests,opened,entries}}

const data={scope:'ai',recipient:'ai',url:'/local/00000000-0000-4000-8000-4ba7215b54d2?workspace=ai',jobId:'a'.repeat(32),receipt:'b'.repeat(32),title:'Codex · 会话已完成',body:'点按查看'};
test('closed-page push displays a system notification, receipts only after display and opens exact workspace thread',async()=>{const s=boot();let p;s.handlers.push({data:{json:()=>data},waitUntil:v=>p=v});await p;assert.equal(s.shown.length,1);assert.equal(s.requests[0][0],'/sync/v1/w/ai/push-received');assert.equal(JSON.parse(s.requests[0][1].body).jobId,data.jobId);assert.equal(s.shown[0].options.renotify,false);let closed=false;s.handlers.notificationclick({notification:{data:s.shown[0].options.data,close:()=>closed=true},waitUntil:v=>p=v});await p;assert(closed);assert.equal(s.opened[0],'http://localhost:3080'+data.url+'&fromNotification=1');});
test('foreign destinations and mismatched workspace cannot display or navigate',async()=>{for(const url of ['https://evil.invalid/?workspace=ai','/local/00000000-0000-4000-8000-4ba7215b54d2?workspace=secondary','/api/context?workspace=ai']){const s=boot();let p;s.handlers.push({data:{json:()=>({...data,url})},waitUntil:v=>p=v});await p;assert.equal(s.shown.length,0);assert.equal(s.requests.length,0);}});
test('a denied system notification cannot produce a delivered receipt',async()=>{const s=boot();s.self.registration.showNotification=async()=>{throw Error('denied')};let p;s.handlers.push({data:{json:()=>data},waitUntil:v=>p=v});await assert.rejects(p,/denied/);assert.equal(s.requests.length,0);});

test('unassigned devices and the other recipient never display or acknowledge a push',async()=>{for(const recipient of [null,'secondary']){const s=boot({recipient});let p;s.handlers.push({data:{json:()=>data},waitUntil:v=>p=v});await p;assert.equal(s.shown.length,0);assert.equal(s.requests.length,0);}});
test('recipient changes persist without a page and suppress already queued notifications',async()=>{const s=boot();let p,ack;s.handlers.message({data:{type:'SET_NOTIFICATION_RECIPIENT',recipient:'secondary'},source:{url:'http://localhost:3080/?workspace=ai'},ports:[{postMessage:x=>ack=x}],waitUntil:x=>p=x});await p;assert.equal(ack.recipient,'secondary');s.handlers.push({data:{json:()=>data},waitUntil:x=>p=x});await p;assert.equal(s.shown.length,0);s.handlers.notificationclick({notification:{data:{scope:'ai',url:data.url},close(){}},waitUntil:x=>p=x});await p;assert.equal(s.opened.length,0);const updated={...data,scope:'secondary',recipient:'secondary',url:data.url.replace('workspace=ai','workspace=secondary')};s.handlers.push({data:{json:()=>updated},waitUntil:x=>p=x});await p;assert.equal(s.shown.length,1);});
test('foreign messages cannot change the notification recipient',async()=>{const s=boot();let p;s.handlers.message({data:{type:'SET_NOTIFICATION_RECIPIENT',recipient:'secondary'},source:{url:'https://evil.invalid/'},waitUntil:x=>p=x});await p;s.handlers.push({data:{json:()=>data},waitUntil:x=>p=x});await p;assert.equal(s.shown.length,1);});
