import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../public/native-workbench-plugins.js',import.meta.url),'utf8');
const navigation=await readFile(new URL('../public/native-navigation.js',import.meta.url),'utf8');
function setup(){
 const listeners={},entries=[{state:{},url:'http://localhost:3080/?workspace=ai&nativeList=1'}];let index=0,exits=0,list=true;
 const location={};const sync=()=>Object.assign(location,Object.fromEntries(['href','origin','pathname','search','hash'].map(k=>[k,new URL(entries[index].url)[k]])));sync();
 const emit=()=>{sync();for(const fn of listeners.popstate||[])fn({state:history.state});};
 const history={get state(){return entries[index].state},pushState(state,t,url){entries.splice(index+1);entries.push({state,url:new URL(url,location.href).href});index++;sync()},replaceState(state,t,url){entries[index]={state,url:new URL(url,location.href).href};sync()},back(){if(!index){exits++;return;}index--;emit()},forward(){if(index+1<entries.length){index++;emit()}}};
 const node=()=>({children:[],dataset:{},style:{},append(...v){this.children.push(...v)},replaceChildren(...v){this.children=v},setAttribute(){},remove(){},getBoundingClientRect(){return {width:0}}});
 const document={documentElement:node(),body:node(),createElement:node,querySelector(){return null},querySelectorAll(){return []},addEventListener(){},visibilityState:'visible'};
 const window={__BETTER_CODEX_SCOPE__:{id:'ai',nativeList:true},__BETTER_CODEX_NATIVE_SIDEBAR__:{get isList(){return list},show(){list=true},openWorkbench(){list=false}},fetch:async path=>({ok:true,json:async()=>path==='/api/context'?{token:'test'}:path.endsWith('/plugins')?{data:[{id:'portfolio',label:'投资'}]}:{kind:'portfolio',snapshot:{totals:{dailyPnlCny:2,unrealizedPnlCny:-1},positions:[]}}})};window.parent=window;
 const context=vm.createContext({window,document,history,location,URL,navigator:{onLine:true},setTimeout(){},setInterval(){},Event:class{},innerWidth:360,addEventListener:(name,fn)=>(listeners[name]??=[]).push(fn)});vm.runInContext(navigation,context);vm.runInContext(source,context);
 return {window,document,history,entries,get exits(){return exits},get list(){return list}};
}
test('plugin system Back reaches list; refresh adds no history; forward restores plugin',async()=>{const x=setup();await x.window.__BETTER_CODEX_NATIVE_WORKBENCH__.open('portfolio');assert.equal(x.entries.length,2);assert.equal(x.list,false);await x.window.__BETTER_CODEX_NATIVE_WORKBENCH__.open('portfolio');assert.equal(x.entries.length,2);x.history.back();assert.equal(x.exits,0);assert.equal(x.list,true);assert.equal(x.window.__BETTER_CODEX_NATIVE_WORKBENCH__.current,null);x.history.forward();await new Promise(r=>setImmediate(r));assert.equal(x.window.__BETTER_CODEX_NATIVE_WORKBENCH__.current,'portfolio');x.window.__BETTER_CODEX_NATIVE_WORKBENCH__.close();assert.equal(x.list,true);assert.equal(x.exits,0);});
test('P&L styling uses numerical sign without coloring missing values',async()=>{const x=setup();await x.window.__BETTER_CODEX_NATIVE_WORKBENCH__.open('portfolio');const all=[];function walk(n){all.push(n);for(const c of n.children||[])walk(c)}walk(x.document.body);assert.ok(all.some(n=>n.className==='betterCodex-pnl-up'&&n.textContent==='+2'));assert.ok(all.some(n=>n.className==='betterCodex-pnl-down'&&n.textContent==='-1'));assert.ok(!all.some(n=>n.textContent==='—'&&/betterCodex-pnl/.test(n.className||'')));});
