import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../public/native-status-recovery.js',import.meta.url),'utf8');
const id='00000000-0000-4000-8000-4ba7215b54d2',turnId='00000000-0000-4000-8000-f82fe242e2a8';
function setup({canonical=false,summaryOnly=false}={}){
 const listeners=new Map(),events=[],c={id,resumeState:'resumed',threadRuntimeStatus:{type:'active',activeFlags:[]},turns:[{turnId,status:'inProgress',items:[{text:'preserved'}]}],draft:'preserved'};
 if(canonical)c.turnHistory={kind:'canonical',history:{entitiesByKey:{['turn:'+turnId]:c.turns[0]}}};
 const summaries=[{conversationId:id,threadRuntimeStatus:c.threadRuntimeStatus}];
 const client={hostId:'local',addNotificationCallback:(m,fn)=>listeners.set(m,fn),getConversation:()=>summaryOnly?null:c,getCachedConversations:()=>summaryOnly?[]:[c],getThreadSummaries:()=>summaries,
  onNotification(method,params){events.push(method);c.threadRuntimeStatus=params.status;summaries[0].threadRuntimeStatus=params.status;listeners.get(method)?.({params});},
  updateTurnState(_id,target,fn){assert.equal(target,turnId);fn(c.turns[0]);}};
 const window={__BETTER_CODEX_SCOPE__:{id:'ai'}};vm.runInNewContext(source,{window});const recovery=window.__BETTER_CODEX_NATIVE_STATUS_RECOVERY__;recovery.register(client);
 const record=(method,result,extra={})=>({source:'native',scope:'ai',threadId:id,payload:{method,result},...extra});
 return {c,client,events,recovery,record,notify:(m,params)=>listeners.get(m)?.({params}),read:(method,result,extra,stamp=recovery.beginRead(id))=>recovery.acceptRead(method,{threadId:id},record(method,result,extra),stamp)};
}
test('a verified idle read clears a resumed sidebar status without a completion notification',()=>{const x=setup();x.read('thread/read',{thread:{id,status:{type:'idle'}}});assert.equal(x.c.threadRuntimeStatus.type,'idle');assert.deepEqual(x.events,['thread/status/changed']);assert.equal(x.c.resumeState,'resumed');assert.equal(x.c.draft,'preserved');});
test('verified terminal turns repair stale loaded progress in both native history forms',()=>{for(const canonical of [false,true])for(const status of ['completed','failed','interrupted']){const x=setup({canonical});x.read('thread/turns/list',{data:[{id:turnId,status,durationMs:42}]});assert.equal(x.c.turns[0].status,status);assert.equal(x.c.turns[0].items[0].text,'preserved');assert.equal(x.c.turns[0].durationMs,42);assert.equal(x.events.length,0);}});
test('cached, foreign and deleted reads cannot declare a task complete',()=>{for(const extra of [{source:'cloud-cache'},{scope:'secondary'},{deleted:true},{threadId:'other'}]){const x=setup();x.read('thread/read',{thread:{id,status:{type:'idle'}}},extra);assert.equal(x.c.threadRuntimeStatus.type,'active');}});
test('a newer turn or status notification supersedes an in-flight idle read',()=>{for(const method of ['turn/started','turn/completed','thread/status/changed','thread/reverted']){const x=setup(),stamp=x.recovery.beginRead(id);x.notify(method,{threadId:id});x.read('thread/read',{thread:{id,status:{type:'idle'}}},{},stamp);x.read('thread/turns/list',{data:[{id:turnId,status:'completed'}]},{},stamp);assert.equal(x.c.threadRuntimeStatus.type,'active');assert.equal(x.c.turns[0].status,'inProgress');assert.equal(x.recovery.diagnostics().supersededReads,2);}});
test('summary-only active rows are corrected and unrelated turn IDs remain untouched',()=>{const x=setup({summaryOnly:true});assert.equal(x.recovery.activeThreadIds()[0],id);x.read('thread/read',{thread:{id,status:{type:'idle'}}});assert.equal(x.client.getThreadSummaries()[0].threadRuntimeStatus.type,'idle');assert.equal(x.recovery.activeThreadIds().length,0);const y=setup();y.read('thread/turns/list',{data:[{id:'another-turn',status:'completed'}]});assert.equal(y.c.turns[0].status,'inProgress');});
test('genuinely active threads continue to run and repeated corrections are idempotent',()=>{const x=setup();x.read('thread/read',{thread:{id,status:{type:'active',activeFlags:[]}}});assert.equal(x.events.length,0);x.read('thread/read',{thread:{id,status:{type:'idle'}}});x.read('thread/read',{thread:{id,status:{type:'idle'}}});assert.equal(x.events.length,1);x.read('thread/turns/list',{data:[{id:turnId,status:'completed'}]});x.read('thread/turns/list',{data:[{id:turnId,status:'completed'}]});assert.equal(x.recovery.diagnostics().turnCorrections,1);});

test('cloud durable ACK responses are authoritative only for an explicitly fresh read',()=>{const x=setup(),fresh=x.recovery.beginRead(id,{fresh:true});x.read('thread/read',{thread:{id,status:{type:'idle'}}},{source:undefined},fresh);assert.equal(x.c.threadRuntimeStatus.type,'idle');for(const extra of [{source:undefined},{source:'cloud-cache'}]){const y=setup();y.read('thread/read',{thread:{id,status:{type:'idle'}}},extra,extra.source==='cloud-cache'?y.recovery.beginRead(id,{fresh:true}):undefined);assert.equal(y.c.threadRuntimeStatus.type,'active');}});
