import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {createOfficialPreviewProxy} from '../src/official-preview-proxy.mjs';
const request=(port,path,headers={})=>new Promise((resolve,reject)=>{http.get({host:'127.0.0.1',port,path,headers},r=>{let body='';r.on('data',b=>body+=b);r.on('end',()=>resolve({status:r.statusCode,headers:r.headers,body}));}).on('error',reject);});
test('official UI is default; explicit legacy fallback, workbench and existing APIs remain intact',async()=>{
 const upstream=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'text/plain','etag':'"official"','cache-control':'private, no-cache'});res.end('official '+req.url);});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));
 const proxy=createOfficialPreviewProxy({upstream:'http://127.0.0.1:'+upstream.address().port});const server=http.createServer((req,res)=>{if(!proxy.route(req,res))res.end('legacy');});await new Promise(r=>server.listen(0,'127.0.0.1',r));const p=server.address().port;
 try {assert.equal((await request(p,'/')).body,'official /');assert.equal((await request(p,'/',{cookie:'betterCodex_official_preview=0'})).body,'legacy');assert.equal((await request(p,'/workbench?workspace=ai')).body,'legacy');const enter=await request(p,'/ui/official?workspace=secondary');assert.equal(enter.status,303);assert.equal(enter.headers.location,'/?workspace=secondary');assert.match(enter.headers['set-cookie'][0],/HttpOnly; Secure; SameSite=Lax/);
 const headers={cookie:'betterCodex_official_preview=1'};const official=await request(p,'/official-patched-v8/assets/a.js',headers);assert.equal(official.body,'official /official-patched-v8/assets/a.js');assert.equal(official.headers.etag,'"official"');assert.equal((await request(p,'/api/w/ai/events',headers)).body,'legacy');assert.equal((await request(p,'/healthz',headers)).body,'legacy');const exit=await request(p,'/ui/legacy',headers);assert.equal(exit.status,303);assert.match(exit.headers['set-cookie'][0],/betterCodex_official_preview=0/);
 let touched=false;const fakeSocket={end:()=>{touched=true}};assert.equal(proxy.upgrade({url:'/w/ai/ws',headers:{host:'attacker.example',origin:'https://attacker.example',cookie:'betterCodex_official_preview=1'}},fakeSocket,Buffer.alloc(0)),false);assert.equal(touched,false);
 } finally {await new Promise(r=>server.close(r));await new Promise(r=>upstream.close(r));}
});
