import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {createRequire} from 'node:module';import {OfficialGit} from '../src/official-git.mjs';
const require=createRequire('${BETTER_CODEX_HOME}/.better-codex/official-runtime-20260908/opencodex-pinned/package.json'),{WebSocketServer}=require('ws');
test('Git worker requests are correlated and scoped; mutations and foreign notifications cannot pass',async t=>{
 const server=http.createServer(),wss=new WebSocketServer({server}),received=[],out=[],sockets=[];wss.on('connection',socket=>{sockets.push(socket);socket.on('message',raw=>{const m=JSON.parse(raw);if(m.type==='hello'){socket.send(JSON.stringify({type:'hello-ack',clientId:m.clientId}));return;}received.push(m);const frame=m.request.args[0];if(frame.type==='worker-request')socket.send(JSON.stringify({channel:'codex_desktop:worker:git:for-view',payload:{type:'worker-response',workerId:'git',response:{id:frame.request.id,method:frame.request.method,result:{type:'ok',value:{root:'${BETTER_CODEX_WORKSPACE}'}}}}}));});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const bridge=new OfficialGit({upstream:'http://127.0.0.1:'+server.address().port,files:{resolve:async()=>{}},send:(c,m)=>out.push(m)}),client={scope:'ai'};t.after(async()=>{bridge.close(client);for(const s of sockets)s.terminate();wss.close();await new Promise(r=>server.close(r));});
 const frame={type:'worker-request',workerId:'git',request:{id:'renderer-id',method:'stable-metadata',params:{cwd:'${BETTER_CODEX_WORKSPACE}',hostConfig:{id:'local',kind:'local'}}}};await bridge.invoke(client,frame);for(let i=0;i<30&&!out.length;i++)await new Promise(r=>setTimeout(r,5));assert.equal(out[0].payload.response.id,'renderer-id');assert.notEqual(received[0].request.args[0].request.id,'renderer-id');
 await bridge.invoke(client,{...frame,request:{...frame.request,id:'deny',params:{cwd:'${BETTER_CODEX_SECONDARY_WORKSPACE}'}}});assert.equal(out.at(-1).payload.response.result.type,'error');assert.equal(received.length,1);
 await bridge.invoke(client,{...frame,request:{...frame.request,id:'write',method:'push'}});assert.equal(out.at(-1).payload.response.result.type,'error');assert.equal(received.length,1);
 const before=out.length;sockets[0].send(JSON.stringify({channel:'codex_desktop:worker:git:for-view',payload:{type:'worker-event',workerId:'git',event:{type:'git-repo-changed',root:'${BETTER_CODEX_SECONDARY_WORKSPACE}',hostId:'local'}}}));await new Promise(r=>setTimeout(r,10));assert.equal(out.length,before);
});
