import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {ViewState,parseSSE,DraftStore,isWorkbenchRoute,workbenchReturnUrl} from '../public/state.mjs';
test('public workbench path and old query route retain a same-scope native return URL',()=>{
 const id='00000000-0000-4000-8000-4ba7215b54d2',back='/local/'+id+'?workspace=ai',url='http://localhost:3080/workbench?workspace=ai&returnTo='+encodeURIComponent(back);assert(isWorkbenchRoute(url));assert(isWorkbenchRoute('http://localhost:3080/?view=workbench'));assert(!isWorkbenchRoute('http://localhost:3080/?workspace=ai'));assert.equal(workbenchReturnUrl(url,'ai'),back);assert.equal(workbenchReturnUrl(url,'secondary'),'/ui/official?workspace=secondary');assert.equal(workbenchReturnUrl('http://localhost:3080/workbench?returnTo=https://attacker.invalid/','ai'),'/ui/official?workspace=ai');
});
test('actual workbench bootstrap and foreground recovery never load or connect the legacy executor',async()=>{
 const source=(await readFile(new URL('../public/app.mjs',import.meta.url),'utf8')).replace(/^import[^\n]+\n/,'');const elements=new Map(),events={},calls=[];
 const element=()=>({value:'',hidden:false,style:{setProperty(){}},classList:{toggle(){},add(){},remove(){}},replaceChildren(){},append(){},addEventListener(){},setAttribute(){}});
 const location={href:'http://localhost:3080/workbench?workspace=ai',origin:'http://localhost:3080'},storage={getItem:()=>null,setItem(){},removeItem(){}};
 const context={ViewState,parseSSE,DraftStore,isWorkbenchRoute,workbenchReturnUrl,URL,AbortController,location,sessionStorage:storage,document:{getElementById:id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id);},createElement:element,body:element(),documentElement:element(),addEventListener(){},visibilityState:'visible'},window:{addEventListener:(k,f)=>events[k]=f},history:{replaceState:(s,t,u)=>location.href=String(u)},navigator:{},clearTimeout(){},clearInterval(){},setTimeout:()=>1,setInterval:()=>{throw Error('Legacy timer must not start on workbench');},fetch:async(url)=>{calls.push(String(url));if(String(url)==='/api/context')return {ok:true,json:async()=>({token:'scoped-test',generation:'test'})};if(String(url).endsWith('/api/w/ai/plugins'))return {ok:true,json:async()=>({data:[]})};throw Error('Unexpected legacy request '+url);}};
 await vm.runInNewContext(source,context);await events.pageshow();assert.equal(elements.get('workbench').hidden,false);assert.equal(elements.get('catalog').hidden,true);assert.equal(elements.get('back').hidden,true);assert.equal(calls.length,4);assert(!calls.some(x=>/threads|events|snapshot/.test(x)));
});
