import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {patchPostAckEmptyQueue,patchPostAckEmptyQueueAdapter} from '../src/official-post-ack-queue.mjs';
const base=new URL('../../../runtime/critical-path-isolation-20261005/pass9/candidate/android-ui/files/official-patched-v1164/assets/',import.meta.url),input=await readFile(process.env.DSH_SUBMISSION_INITIAL||new URL('app-initial-cadb12d4a15e.js',base),'utf8'),primary=await readFile(process.env.DSH_SUBMISSION_PRIMARY||new URL('app-primary-b231d8da4368.js',base),'utf8'),rawQueue=await readFile(process.env.DSH_SUBMISSION_QUEUE||new URL('../public/native-queue-client.js',import.meta.url),'utf8'),queue=process.env.DSH_SUBMISSION_FINAL==='1'?rawQueue:patchPostAckEmptyQueueAdapter(rawQueue),patched=process.env.DSH_SUBMISSION_FINAL==='1'?input:patchPostAckEmptyQueue(input);
const originalInitial=process.env.DSH_SUBMISSION_FINAL==='1'?await readFile(process.env.DSH_SUBMISSION_ORIGINAL||new URL('app-initial-cadb12d4a15e.js',base),'utf8'):input;
if(process.env.DSH_SUBMISSION_FINAL==='1'){assert(patched.includes('this.options.storage.dshCanSkipEmptyResume'));assert(queue.includes('const dshEmptyQueueReads=new Map();'));}
const A='11111111-1111-4111-a111-111111111111',OTHER='22222222-2222-4222-a222-222222222222';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});promise.catch(()=>{});return{promise,resolve,reject};};
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve));};
const cut=(s,a,b)=>{const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i,a);return s.slice(i,j);};
function fixture({before=false,messages=[],storeGate=null,readGate=null}={}){
 const sdk=before?originalInitial:patched,events=new Map(),counters={reads:0,updates:0,loads:0},client={disposed:false},native={authority:'mac-native',state:{[A]:structuredClone(messages)},revisions:{[A]:'native-revision-one'}};
 const ctx={zx:class{},Ddn:[],Edn:()=>{},uFt:()=>false,pFt:'isolated unsupported',getMessageQueueMode:()=>{},client,activeQueueClient:client,window:{__DSH_EXECUTION_CONNECTED__:true},navigator:{onLine:true},Object,Map,Set,Promise,structuredClone,console,
 addEventListener:(name,fn)=>{if(!events.has(name))events.set(name,new Set());events.get(name).add(fn);},removeEventListener:(name,fn)=>events.get(name)?.delete(fn),state:{[A]:[]},revisions:{},loaded:false,refreshing:null,inflightCommands:new Map(),terminalWrites:new Map(),submissionRequests:new Map(),receiptWaiting:new Set(),controlRequests:new Map(),sequence:0,scheduleSnapshot:()=>{},receiptClientActive:()=>!client.disposed&&!ctx.q?.disposed,
 api:async(request)=>{assert.equal(request,null,'test never submits a queue/model command');counters.reads++;if(readGate)await readGate.promise;return structuredClone(native);}};
 vm.createContext(ctx);const klass=cut(sdk,'Odn=class extends zx{','}));function Adn(');vm.runInContext('var '+klass+';globalThis.Coordinator=Odn;',ctx);
 const options={logger:{warning(){}},getStreamRole:()=>({role:'owner'}),canSend:()=>false,onQueueChanged:()=>{},storage:{read:()=>({isLoading:!ctx.loaded,value:ctx.state}),load:async()=>{counters.loads++;return ctx.state;},update:async fn=>{counters.updates++;ctx.state=fn(structuredClone(ctx.state));if(storeGate)await storeGate.promise;return ctx.state;}}};
 const q=new ctx.Coordinator(options);ctx.q=q;
 vm.runInContext(cut(queue,'const applied=new Map(),reads=new Map(),mutating=new Set();','const feedback=')+cut(queue,'function accept(result,ticket=++sequence,readScope=null,','function publish()')+'q.options.storage.dshCanSkipEmptyResume='+cut(queue,'dshCanSkipEmptyResume:id=>{','read:()=>').replace('dshCanSkipEmptyResume:','').replace(/,\s*$/,'')+';',ctx);
 // Real KIt action -> zQr submitted callback -> real SDK private mutation path.
 Object.assign(ctx,{YIt:{c:n=>Array(n).fill(Symbol.for('react.memo_cache_sentinel'))},HQr:{c:n=>Array(n).fill(Symbol.for('react.memo_cache_sentinel'))},UQr:{useState:()=>[false,()=>{}]},WQr:{jsx:()=>({})},yYr:()=>{},VQr:()=>false,t_e:'Interrupted before the steer was accepted.',JPr:()=>{},qv:{},yB:{},zx:()=>({get:()=>q.read(A).messages}),QE:()=>({getHostId:()=> 'local'}),rw:()=>q.read(A).messages,xO:()=>({getTurnCoordinator:async()=>q}),qIt:()=>{},WIt:()=>{}});
 vm.runInContext(cut(primary,'function KIt(','async function qIt(')+cut(primary,'function JIt(','var YIt,')+cut(primary,'function zQr(','var HQr,')+'globalThis.afterAck=()=>zQr({scope:{},hostId:"local",messages:q.read("'+A+'").messages,actions:KIt("'+A+'").actions,canShow:true,submit(){}}).submitted(false);globalThis.retireSource=()=>dshRetireEmptyQueue();globalThis.holdRead=()=>reads.set("'+A+'",Promise.resolve());globalThis.holdMutation=()=>mutating.add("'+A+'");globalThis.markMutation=()=>{dshQueueMutationPending++;};globalThis.finishMutation=()=>{dshQueueMutationPending--;};',ctx);
 const seed=async()=>{await ctx.load(A);q.messages.set(A,{messages:structuredClone(ctx.state[A]),refreshing:false});};
 return{ctx,q,native,counters,events,seed,afterAck:ctx.afterAck,pulse:name=>{for(const fn of events.get(name)||[])fn();}};
}
test('old exact empty-queue callback waits mutation storage; new fresh empty callback has zero persistence/network side effects',async()=>{const hold=deferred(),old=fixture({before:true,storeGate:hold});await old.seed();let oldDone=false;const prior=old.afterAck().then(()=>oldDone=true);await flush();assert.equal(oldDone,false);assert.equal(old.counters.updates,1);const next=fixture({storeGate:hold});await next.seed();await next.afterAck();assert.equal(next.counters.updates,0);assert.equal(next.counters.loads,0);assert.equal(next.counters.reads,1,'only setup Native queue GET, no no-op reload/sync');hold.resolve();await prior;});
test('non-empty paused queue retains actual SDK persistence/serial wait and original marker transformation',async()=>{const hold=deferred(),f=fixture({messages:[{id:OTHER,pausedReason:'Interrupted before the steer was accepted.'}],storeGate:hold});await f.seed();let done=false;const work=f.afterAck().then(()=>done=true);await flush();assert.equal(done,false);assert.equal(f.counters.updates,1);assert.equal(f.ctx.state[A][0].pausedReason,undefined);hold.resolve();await work;});
test('cold cached empty state without a real Native GET cannot authorize no-op',async()=>{const f=fixture();f.ctx.loaded=true;f.ctx.state={[A]:[]};f.q.messages.set(A,{messages:[],refreshing:false});await f.afterAck();assert.equal(f.counters.updates,1);});
for(const kind of ['source','auth','stopUnknown','pendingReceipt','readInFlight','mutating','adapterWrite','sdkPending','sdkRefreshing','nativeRevision','differentStoredQueue'])test('empty shortcut refuses '+kind+' and preserves normal path',async()=>{const f=fixture();await f.seed();if(kind==='source')f.pulse('dsh:app-host-state');if(kind==='auth')f.pulse('dsh:authentication-required');if(kind==='stopUnknown')f.ctx.controlRequests.set('stop',A);if(kind==='pendingReceipt')f.ctx.receiptWaiting.add(A);if(kind==='readInFlight')f.ctx.holdRead();if(kind==='mutating')f.ctx.holdMutation();if(kind==='adapterWrite')f.ctx.markMutation();if(kind==='sdkPending')f.q.pending.set(OTHER,{count:1,committedMessages:[],broadcast:undefined});if(kind==='sdkRefreshing')f.q.queueRefresh=Promise.resolve();if(kind==='nativeRevision')f.ctx.revisions[A]='changed';if(kind==='differentStoredQueue')f.ctx.state[A]=[{id:OTHER,pausedReason:'Interrupted before the steer was accepted.'}];await f.afterAck();assert.equal(f.counters.updates,1);});
test('old-generation held Native queue GET does not create a fresh epoch capability',async()=>{const held=deferred(),f=fixture({readGate:held}),work=f.seed();await flush();f.pulse('dsh:execution-state');held.resolve();await work;assert.equal(f.q.options.storage.dshCanSkipEmptyResume(A),false);await f.afterAck();assert.equal(f.counters.updates,1);});
test('retired coordinator retains rejection, unknown result is never retried or reclassified queued',async()=>{const f=fixture();await f.seed();f.q.dispose();await assert.rejects(f.afterAck(),/retired/);assert.equal(f.counters.updates,0);assert.equal(f.counters.reads,1);});
test('real Native adapter update tracker covers held and failed serialization, without model writes',async()=>{const f=fixture();await f.seed();const gate=deferred();Object.assign(f.ctx,{writes:gate.promise,reconcile:async()=>{},preparedInput:async()=>{throw Error('No model input expected');},publish:()=>{},feedback:()=>{},refresh:()=>{},checkpointSnapshot:()=>Promise.resolve(),snapshotEpoch:0,ackDeadlines:new WeakMap(),crypto:{randomUUID:()=>OTHER}});vm.runInContext(cut(queue,'q.options.storage={','const sendQueuedMessageNow='),f.ctx);const write=f.q.options.storage.update(value=>value);assert.equal(f.q.options.storage.dshCanSkipEmptyResume(A),false);gate.resolve();await write;await flush();assert.equal(f.q.options.storage.dshCanSkipEmptyResume(A),true);const failed=f.q.options.storage.update(()=>{throw Error('isolated update failure');});await assert.rejects(failed,/isolated update failure/);await flush();assert.equal(f.q.options.storage.dshCanSkipEmptyResume(A),true);assert.equal(f.counters.reads,1);});
test('real SDK pending queue write remains a serial fence for the next empty callback',async()=>{const gate=deferred(),f=fixture({storeGate:gate});await f.seed();const first=f.q.clearQueuedMessages(A);await flush();assert.equal(f.counters.updates,1);let done=false;const second=f.afterAck().then(()=>done=true);await flush();assert.equal(done,false);assert.equal(f.counters.updates,1);gate.resolve();await Promise.all([first,second]);assert.equal(f.counters.updates,2);});
test('patches are idempotent, unsupported surfaces and changed contracts fail closed',()=>{assert.equal(patchPostAckEmptyQueue(patched),patched);assert.equal(patchPostAckEmptyQueueAdapter(queue),queue);assert.throws(()=>patchPostAckEmptyQueue(input,{surface:'primary'}),/initial surface/);assert.throws(()=>patchPostAckEmptyQueue('other SDK'),/contract changed/);assert.throws(()=>patchPostAckEmptyQueueAdapter('other adapter'),/contract changed/);});
