import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,symlink,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {readJsonArtifact} from '${BETTER_CODEX_WORKSPACE}/agent/tools/json-artifacts.mjs';
const dir=await mkdtemp(path.join(os.tmpdir(),'agent-catalog-'));
const ai=path.join(dir,'ai'),secondary=path.join(dir,'secondary');
await mkdir(path.join(ai,'Invest'),{recursive:true});await mkdir(path.join(secondary,'SecondaryProject'),{recursive:true});
const sites=path.join(dir,'sites.json'),config=path.join(dir,'workspaces.json');
await writeFile(sites,JSON.stringify({sites:[{id:'invest',project_id:'invest',name:'投资',status:'active',canonical_url:'https://example.invalid/',access_model:'private',secret_references:['MUST_NOT_ESCAPE']},{id:'secondary',name:'书架',status:'active',canonical_url:'https://secondary.invalid/',access_model:'private'}]}));
await writeFile(config,JSON.stringify({schema:'agent-workspaces.v1',siteRegistry:sites,workspaces:{ai:{id:'ai',root:ai,projectRegistry:'projects.json',plugins:[]},secondary:{id:'secondary',root:secondary,projectRegistry:'projects.json',plugins:[]}}}));
await writeFile(path.join(ai,'projects.json'),JSON.stringify({projects:[{id:'invest',name:'Invest',root:'Invest',lifecycle:'active'},{id:'hidden',root:'Invest',lifecycle:'on_demand',default_visibility:'hidden'},{id:'retired',root:'Invest',lifecycle:'retired'},{id:'foreign',root:path.join(secondary,'SecondaryProject'),lifecycle:'active'}]}));
await writeFile(path.join(secondary,'projects.json'),JSON.stringify({projects:[{id:'secondary-project',root:'SecondaryProject',lifecycle:'active',site_ids:['secondary']}]}));
process.env.AI_WORKSPACES_CONFIG=config;
const {projectCatalog,projectDetails}=await import('${BETTER_CODEX_WORKSPACE}/agent/runtime/lib/projects.mjs');
test.after(()=>rm(dir,{recursive:true,force:true}));
test('catalog excludes retired, hidden and foreign projects and private site metadata',async()=>{
 const a=await projectCatalog('ai'),z=await projectCatalog('secondary');
 assert.deepEqual(a.projects.map(p=>p.id),['invest']);assert.deepEqual(z.projects.map(p=>p.id),['secondary-project']);
 assert.equal(a.projects[0].surfaces[0].url,'https://example.invalid/');
 assert.ok(!JSON.stringify(a).includes('MUST_NOT_ESCAPE'));await assert.rejects(projectDetails('ai','secondary-project'),e=>e.code===404);
});
test('artifact reader rejects traversal, symlink escapes and oversized files',async()=>{
 await writeFile(path.join(dir,'outside.json'),'{}');await symlink(path.join(dir,'outside.json'),path.join(ai,'escape.json'));
 assert.equal((await readJsonArtifact('../outside.json',{root:ai})).reason,'policy');
 assert.equal((await readJsonArtifact('escape.json',{root:ai})).reason,'policy');
 assert.equal((await readJsonArtifact('projects.json',{root:ai,maxBytes:2})).reason,'oversized');
 const value=await readJsonArtifact('projects.json',{root:ai});assert.match(value.revision,/^[a-f0-9]{64}$/);
});
