import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../public/native-pwa-preferences.js',import.meta.url),'utf8');
function fixture({fail=false,quota=null,quotaError=false,push=false,owner=null,workspace='ai',pushSupported=false}={}){
 const nodes=[],events=new Map(),timers=new Map();let reloads=0,prepares=0,reads=0,timerId=0;let recipient=owner,enabled=false;const pushCalls=[];
 const root={inert:false};
 const element=tag=>{const n={tag,children:[],textContent:'',style:{},listeners:{},append(...a){this.children.push(...a);},replaceChildren(...a){this.children=[...a];},setAttribute(k,v){this[k]=v;},addEventListener(k,f){this.listeners[k]=f;},remove(){this.removed=true;},focus(){},click(){return this.onclick?.();},querySelector(){return this.children.find(x=>x.tag==='button');}};nodes.push(n);return n;};
 const installing={state:'installing',addEventListener(k,f){this.listener=f;},removeEventListener(){}};
 const worker={postMessage(message,ports){if(message.type==='PREPARE_NATIVE_CACHE'){assert.equal(installing.state,'installed');prepares++;queueMicrotask(()=>ports[0].pair.onmessage({data:{ready:!fail,version:'new'}}));}else if(message.type==='SET_NOTIFICATION_RECIPIENT')queueMicrotask(()=>ports[0].pair.onmessage({data:{recipient:message.recipient}}));else if(message.type==='ACTIVATE_UPDATE')events.get('controllerchange')();}};
 const registration={installing:null,waiting:null,active:worker,addEventListener(){},async update(){this.installing=installing;setImmediate(()=>{installing.state='installed';this.waiting=worker;installing.listener();});}};
 const sw={addEventListener(k,f){events.set(k,f);},removeEventListener(k){events.delete(k);},getRegistration:async()=>registration};
 const context={document:{visibilityState:'visible',createElement:element,body:element('body'),getElementById:()=>root,addEventListener(k,f){events.set(k,f)},removeEventListener(k){events.delete(k)}},navigator:{serviceWorker:sw},location:{href:'https://example.test/?workspace=ai',reload(){reloads++;}},history:{state:{},pushState(s){this.state=s;},back(){this.state={};events.get('popstate')();}},setTimeout,clearTimeout,setInterval(f,ms){timers.set(++timerId,{f,ms});return timerId;},clearInterval(id){timers.delete(id);},removeEventListener(k){events.delete(k)},CustomEvent:class{},addEventListener(k,f){events.set(k,f);},MessageChannel:class{constructor(){this.port1={close(){}};this.port2={pair:this.port1};}}};
 context.window={__BETTER_CODEX_SCOPE__:{id:workspace},__BETTER_CODEX_UI_RELEASE__:{version:'old'},__BETTER_CODEX_DEVICE_SETTINGS__:{getDeviceKey:()=> 'a'.repeat(64),setOwner(){}},fetch:async()=>({ok:true,json:async()=>({version:'new'})}),dispatchEvent(){}};
 if(quota){context.window.__BETTER_CODEX_NATIVE_CACHE__={meta:async()=>quota};context.window.__BETTER_CODEX_READ_ACCOUNT_LIMITS__=async()=>{reads++;if(quotaError)throw Error('连接恢复后可刷新额度');return quota;};}
 if(push){context.window.fetch=async(url,options={})=>{let result={version:'new'};if(url.includes('/push-')){const body=options.body?JSON.parse(options.body):null;pushCalls.push({url,body});if(url.endsWith('/push-config'))result={available:true,publicKey:'mock-public-key'};else if(url.endsWith('/push-device-owner')){recipient=body.recipient;enabled=false;result={recipient};}else if(url.endsWith('/push-subscribe')){enabled=true;result={enabled};}else if(url.endsWith('/push-disable')){enabled=false;result={enabled};}else result={recipient,enabled};}return{ok:true,json:async()=>result};};}
 if(pushSupported){context.window.PushManager={};context.window.Notification=context.Notification={permission:'granted',requestPermission:async()=>'granted'};registration.pushManager={getSubscription:async()=>({toJSON:()=>({endpoint:'mock-only'})})};sw.ready=Promise.resolve(registration);}
 vm.runInNewContext(source,context);
 return {nodes,root,context,timers,pushCalls,get recipient(){return recipient},get reads(){return reads},tick(){for(const {f} of timers.values())f()},prefs:context.window.__BETTER_CODEX_PWA_PREFERENCES__,counts:()=>({reloads,prepares})};
}
const settle=()=>new Promise(resolve=>setTimeout(resolve,30));
test('settings renders independently of native dialog and closes through browser back',async()=>{const f=fixture();await f.prefs.open();assert(f.nodes.some(n=>n.role==='dialog'&&n.children.length));assert.equal(f.root.inert,true);f.nodes.find(n=>n.textContent==='完成').click();assert.equal(f.root.inert,false);});
test('update waits for installing worker, prepares and activates before reload',async()=>{const f=fixture();await f.prefs.open({update:true});await settle();assert.deepEqual(f.counts(),{reloads:1,prepares:1});});
test('failed cache preparation is visible and never reloads the current task',async()=>{const f=fixture({fail:true});await f.prefs.open({update:true});await settle();assert.equal(f.counts().reloads,0);assert(f.nodes.some(n=>n.textContent==='新版资源下载失败，请稍后再试'));});

const quota={checkedAt:1789200000000,data:{buckets:[{name:'Codex',plan:'pro',primary:{usedPercent:79,windowDurationMins:10080,resetsAt:1789643097},secondary:null,credits:{balance:'0'}}],resetsAvailable:2}};
test('quota renders actual remaining percentage and reset time without inventing a second window',async()=>{const f=fixture({quota});await f.prefs.open();await settle();assert(f.nodes.some(n=>n.textContent==='每周额度剩余 21%'));assert(f.nodes.some(n=>n.tag==='progress'&&n.value===21));assert(f.nodes.some(n=>n.textContent==='可用额度重置：2 次'));assert(!f.nodes.some(n=>n.textContent.includes('5 小时')));assert(f.nodes.some(n=>n.textContent.startsWith('已更新 · ')));});
test('quota failure preserves the last snapshot and visibly labels it cached',async()=>{const f=fixture({quota,quotaError:true});await f.prefs.open();await settle();assert(f.nodes.some(n=>n.tag==='progress'&&n.value===21));assert(f.nodes.some(n=>n.textContent.startsWith('缓存 · 最近读取 ')&&n.textContent.includes('连接恢复后可刷新额度')));});

test('quota has no manual action; automatic read pauses when hidden and stops on close',async()=>{const f=fixture({quota});await f.prefs.open();await settle();assert.equal(f.reads,1);assert(!f.nodes.some(n=>n.tag==='button'&&/额度/.test(n.textContent)));f.tick();await settle();assert.equal(f.reads,2);f.context.document.visibilityState='hidden';f.tick();await settle();assert.equal(f.reads,2);f.nodes.find(n=>n.textContent==='完成').click();assert.equal(f.timers.size,0);f.context.document.visibilityState='visible';f.tick();await settle();assert.equal(f.reads,2);});

test('device owner must be chosen explicitly and changing an existing owner requires confirmation',async()=>{const f=fixture({push:true});await f.prefs.open();await settle();const select=f.nodes.find(n=>n.tag==='select'),save=f.nodes.find(n=>n.textContent==='保存使用者');assert(save.disabled);select.value='ai';select.listeners.change();await save.click();assert.equal(f.recipient,'ai');select.value='secondary';select.listeners.change();await save.click();assert.equal(f.recipient,'ai');assert.equal(save.textContent,'确认切换并关闭通知');await save.click();assert.equal(f.recipient,'secondary');assert(!f.pushCalls.some(c=>/push-subscribe|push-test/.test(c.url)));});
test('viewing SECONDARY still enables notifications only for the saved AI device owner',async()=>{const f=fixture({push:true,owner:'ai',workspace:'secondary',pushSupported:true});await f.prefs.open();await settle();await f.nodes.find(n=>n.textContent==='开启完成通知').click();const call=f.pushCalls.find(c=>c.url.endsWith('/push-subscribe'));assert.equal(call.url,'/sync/v1/w/ai/push-subscribe');assert.equal(call.body.recipient,'ai');assert(!f.pushCalls.some(c=>c.url.endsWith('/push-test')));});
