import nodeTest from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const hasRuntime=!!process.env.DSH_LANE_RUNTIME, actualTest=nodeTest;
const test=(name,fn)=>actualTest(name,{skip:!hasRuntime},fn);
const runtime=hasRuntime?fs.readFileSync(process.env.DSH_LANE_RUNTIME,'utf8'):null,logger=hasRuntime?fs.readFileSync(process.env.DSH_LANE_LOGGER,'utf8'):null;
const REQUEST='11111111-1111-4111-a111-111111111111',THREAD='22222222-2222-4222-a222-222222222222',CONNECTION='33333333-3333-4333-a333-333333333333',EPOCH='44444444-4444-4444-a444-444444444444';
const payload=method=>method==='GET'?{type:'fetch',requestId:REQUEST,url:'vscode://codex/get-global-state',body:JSON.stringify({params:{key:'thread-writable-roots'},private:'PRIVATE_BODY',token:'PRIVATE_TOKEN'})}:{type:'mcp-request',hostId:'local',request:{id:REQUEST,method,params:{threadId:THREAD,input:[{type:'text',text:'PRIVATE_PROMPT'}],privateCookie:'PRIVATE_COOKIE'}}};
function cut(s,a,b){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i,a);return s.slice(i,j);}
function fixture({ready=true,sendThrow=false,logThrow=false}={}){
 class Storage{constructor(){this.values=new Map();}get length(){return this.values.size;}key(i){return[...this.values.keys()][i]??null;}getItem(k){return this.values.get(k)??null;}setItem(k,v){this.values.set(k,String(v));}removeItem(k){this.values.delete(k);}}
 const timers=new Map(),clock={now:1000000,mono:10};let id=0,uuid=0;
 const c={Date:{now:()=>clock.now},performance:{now:()=>clock.mono},navigator:{onLine:true},localStorage:new Storage(),URL,AbortController,crypto:{randomUUID:()=>`00000000-0000-4000-8000-${String(++uuid).padStart(12,'0')}`},location:{pathname:'/local/'+THREAD,href:'https://fixture.invalid/local/'+THREAD,origin:'https://fixture.invalid'},document:{visibilityState:'visible',addEventListener(){}},addEventListener(){},setTimeout:(fn,ms)=>{const n=++id;timers.set(n,{fn,ms});return n;},clearTimeout:n=>timers.delete(n)};
 c.window={__DSH_SCOPE__:{id:'ai',token:'PRIVATE_SCOPE_TOKEN'},__DSH_EXECUTION_CONNECTED__:true,fetch:async()=>({ok:true,json:async()=>({received:true,acknowledgedEventIds:[]})})};vm.runInNewContext(logger,c);const log=c.window.__DSH_CLIENT_LOG__;
 const wire=[],http=[];const socket={readyState:1,__dshDiagnosticId:CONNECTION,__dshFrontEpoch:EPOCH,__dshNativeGeneration:7,__dshNativeConnected:true,send(raw){if(sendThrow)throw Error('isolated send-before-write');wire.push(raw);}};
 const w={WebSocket:{OPEN:1},AbortController,__DSH_CLIENT_LOG__:logThrow?{ipcLane(){throw Error('diagnostic only');},event(){throw Error('diagnostic only');}}:log,__DSH_EXECUTION_METADATA_CONTROL_READY__:()=>true,fetch:async(url,init)=>{http.push({url,init});return{ok:true,status:200,json:async()=>({ok:true,value:{result:'same-result'}})};}};
 const ctx={w,ws:socket,wsReady:ready,clientId:'fixture-client',pendingGatewayIpc:new Map(),gatewayIpcSequence:0,IPC_WS_MAX_PENDING:4096,IPC_WS_MAX_BODY_CHARS:16*1024*1024,IPC_INVOKE_TIMEOUT_MS:30000,scheduler:{setTimeout:c.setTimeout,clearTimeout:c.clearTimeout},modificationEffects:null,CLIENT_DIAGNOSTICS_ENABLED:false,WS_DEBUG_ENABLED:false,ipcDiagnosticSummary:()=>({}),shouldSuppressRoutineIpcDiagnostic:()=>true,clientDiagnostic(){},websocketStateName:()=> 'OPEN',shouldWaitForWsBeforeInvoke:()=>true,waitForGatewayWsReady:async()=>ready,stringifyForIpc:JSON.stringify,shouldRetryGatewayInvoke:()=>false,isTransientGatewayFetchError:()=>false,delay:async()=>{},gatewayAuthHeaders:x=>x,ipcInvokeErrorMessage:()=> 'original invoke failure',Date:{now:()=>clock.now},markGatewayWsReady(){ctx.wsReady=true;},msg:null,socket,rawData:'',parseMs:0,rawChars:0,parseStartedAtMs:0,maybeLogLargeOrSlowWsInbound(){},gatewayWsInboundSummary:()=>({})};
 vm.createContext(ctx);vm.runInContext(cut(runtime,'function invokeGatewayOverWs(','function send')+cut(runtime,'async function invokeGatewayImmediate(','async function invoke(channel,'),ctx);
 const a=runtime.indexOf('if (msg && msg.type === "hello-ack" && msg.clientId === clientId) {'),b=runtime.indexOf('          if (WS_DEBUG_ENABLED)',a);assert(a>=0&&b>a);vm.runInContext('globalThis.handleHello=()=>{'+runtime.slice(a,b)+'}};',ctx);
 const invoke=async p=>{log.ipc('codex_desktop:message-from-view',p);const work=ctx.invokeGatewayImmediate('codex_desktop:message-from-view',[p],p);for(let n=0;n<8;n++)await new Promise(r=>setImmediate(r));if(wire.length){const entry=[...ctx.pendingGatewayIpc.values()][0];entry.resolve({ok:true,value:{result:'same-result'}});}return work;};
 return{ctx,log,clock,wire,http,invoke,socket,hello(message){ctx.msg=message;ctx.handleHello();},events:()=>log.snapshot().events.filter(r=>r.kind==='transport')};
}
test('actual Runtime successful WS producer -> privacy logger records the same RPC id lane',async()=>{const f=fixture(),p=payload('config/read'),out=await f.invoke(p);assert.equal(out.result,'same-result');assert.equal(f.wire.length,1);assert.equal(f.http.length,0);const e=f.events().find(r=>r.routeClass==='native_ws'&&r.stage==='dispatch');assert(e,'old source has no actual underlying lane event');assert.equal(e.method,'config/read');assert.equal(e.rpcIdHash,f.log.hashId(REQUEST));assert.equal(e.connectionId,CONNECTION);assert.equal(e.generation,EPOCH);assert.equal(e.revision,7);assert.equal(e.enabled,true);assert.equal(e.handshakeComplete,true);assert(!JSON.stringify(f.log.snapshot().events).includes('PRIVATE'));});
test('actual Runtime unready HTTP fallback producer logs fetch submission, not a WS wire',async()=>{const f=fixture({ready:false}),p=payload('GET'),out=await f.invoke(p);assert.equal(out.result,'same-result');assert.equal(f.wire.length,0);assert.equal(f.http.length,1);assert.equal(f.http[0].url,'/api/ipc/invoke');const e=f.events().find(r=>r.routeClass==='other');assert.equal(e.stage,'requested');assert.equal(e.component,'native-http');assert.equal(e.method,'GET');assert.equal(e.rpcIdHash,f.log.hashId(REQUEST));assert.equal(e.handshakeComplete,false);assert.equal(e.attempt,1);assert(!f.events().some(r=>r.stage==='dispatch'));assert(!JSON.stringify(f.log.snapshot().events).includes('PRIVATE'));});
test('synchronous send throw logs only original HTTP fallback, without fake WS dispatch',async()=>{const f=fixture({sendThrow:true});await f.invoke(payload('thread/read'));assert.equal(f.wire.length,0);assert.equal(f.http.length,1);assert.equal(f.ctx.pendingGatewayIpc.size,0);assert(!f.events().some(r=>r.routeClass==='native_ws'));assert(f.events().some(r=>r.routeClass==='other'));});
test('hello actual client matching and capability producer -> existing boolean/uuid/numeric privacy fields',()=>{const f=fixture({ready:false});f.hello({type:'hello-ack',clientId:'other',dshReplyProtocol:'dsh-reply-stream-v1',dshEpoch:EPOCH,dshNativeGeneration:7});assert.equal(f.events().length,0);assert.equal(f.ctx.wsReady,false);f.hello({type:'hello-ack',clientId:'fixture-client',dshReplyProtocol:'dsh-reply-stream-v1',dshEpoch:EPOCH,dshNativeGeneration:7,dshNativeConnected:true,cookie:'PRIVATE_COOKIE'});const e=f.events().find(r=>r.method==='initialize');assert.equal(e.handshakeComplete,true);assert.equal(e.selected,true);assert.equal(e.enabled,true);assert.equal(e.revision,7);assert.equal(e.generation,EPOCH);assert(!JSON.stringify(e).includes('PRIVATE'));});
test('missing server reply capability differs from underlying metadata-ready state',()=>{const f=fixture({ready:false});f.ctx.w.__DSH_EXECUTION_METADATA_CONTROL_READY__=()=>false;f.hello({type:'hello-ack',clientId:'fixture-client',dshNativeGeneration:7});const e=f.events().find(r=>r.method==='initialize');assert.equal(e.handshakeComplete,true);assert.equal(e.selected,false);assert.equal(e.enabled,false);assert.equal(e.revision,7);});
test('metadata logger throwing cannot change original wire body, HTTP result or hello acceptance',async()=>{const a=fixture({logThrow:true}),out=await a.invoke(payload('config/read'));assert.equal(out.result,'same-result');assert.equal(a.wire.length,1);assert.equal(a.http.length,0);const b=fixture({ready:false,logThrow:true});assert.equal((await b.invoke(payload('GET'))).result,'same-result');assert.equal(b.http.length,1);b.hello({type:'hello-ack',clientId:'fixture-client'});assert.equal(b.ctx.wsReady,true);});
test('same request body, identity and sequence remain production values after diagnostics',async()=>{const f=fixture(),p=payload('GET');await f.invoke(p);const raw=JSON.parse(f.wire[0]);assert.deepEqual(JSON.parse(JSON.stringify(raw.request.args[0])),p);assert.equal(raw.requestId,'fixture-client:1');assert.equal(raw.request.clientId,'fixture-client');assert.equal(f.ctx.gatewayIpcSequence,1);assert.equal(f.ctx.pendingGatewayIpc.size,1,'diagnostics does not settle or alter pending state');});
