import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {OfficialBoundary} from '../src/official-boundary.mjs';
import {workspace} from '../src/registry.mjs';
const R=path.dirname(fileURLToPath(import.meta.url));
const sdkPath=process.env.DSH_HEAD_CONFIG_SOURCE;
const source=sdkPath?fs.readFileSync(sdkPath,'utf8'):'',originalSdk=process.env.DSH_HEAD_CONFIG_ORIGINAL?fs.readFileSync(process.env.DSH_HEAD_CONFIG_ORIGINAL,'utf8'):source,scopeSource=sdkPath?fs.readFileSync(process.env.DSH_HEAD_CONFIG_SCOPE,'utf8'):'';
const sdkTest=(name,fn)=>test(name,{skip:!sdkPath&&'Requires actual generated SDK/scope/queue fixtures'},fn);
const A='11111111-1111-4111-a111-111111111111',MSG='22222222-2222-4222-a222-222222222222',EPOCH='33333333-3333-4333-a333-333333333333',CWD=workspace('ai').root;
function cut(s,a,b){const i=s.indexOf(a),j=s.indexOf(b,i);assert(i>=0&&j>i,a);return s.slice(i,j);}
function fixture({personality='friendly',allowProjection=true,configError=null,scope='ai',host='local',override=false}={}){
 const calls=[],nativeCalls=[],identity={scope,frontEpoch:EPOCH,nativeGeneration:7,transportGeneration:3,connectionId:'44444444-4444-4444-a444-444444444444',resumeId:'fixture-page-resume'},settings={readExperimentPersonality:async()=>{calls.push('experiment');return 'friendly';}};let current=true,selectedHead=null,allowFast=true,pending=null,projectless=null,hostId=host,sequence=0;
 const fullConfig={model:'fixture-model',model_reasoning_effort:'ultra',service_tier:'priority',sandbox_mode:'danger-full-access',approval_policy:'never',approvals_reviewer:'user',personality,features:{safe_fixture:{nested:[1,true,'value']}},web_search:'cached'};
 const native={generation:7,on(){},start:async()=>{},rpc:async(method,params)=>{nativeCalls.push({method,params});if(method==='config/read'){if(configError)throw configError;return{config:structuredClone(fullConfig),layers:[]};}throw Error('No Native write allowed');}};
 const boundary=new OfficialBoundary({native,journal:{},configProjectionIdentity:allowProjection?s=>({scope:s,frontEpoch:EPOCH,nativeGeneration:native.generation}):null});
 const conversation={cwd:CWD,mode:'default',workspaceKind:'project',latestCollaborationMode:{mode:'default',settings:{model:'fixture-model',reasoning_effort:'high'}},latestModel:'fixture-model',latestReasoningEffort:'high',latestThreadSettings:{serviceTier:'priority'},currentPermissions:{approvalPolicy:'never',approvalsReviewer:'user',sandboxPolicy:{type:'dangerFullAccess'}}};
 const requests={hostId:host,requestPromises:new Map(),sendRequest:async(method,params,options)=>{calls.push({method,params,options});if(method==='config/read'){const id='read-fixture-'+(++sequence),reply=await boundary.call(scope,{id,method,params});return new Promise(resolve=>{const rpc={hostId:host,requestPromises:new Map([[id,{method,queuedAtMs:Date.now(),resolve}]]),clearRequestTimeout(){},releaseRequestCapacity(){},emitRequestLifecycleEvent(){}};ctx.realOnResponse.call(rpc,id,JSON.parse(JSON.stringify(reply)));});}if(method==='thread/read')return{thread:{id:A,status:{type:'idle',activeFlags:[]},threadSource:'user'}};if(method==='configRequirements/read')return{requirements:{featureRequirements:{fast_mode:allowFast}}};throw Error('No protocol write allowed');}};
 let ctx;
 const manager={disposed:false,requestClient:requests,sendRequest:requests.sendRequest,settings,logger:{info(){},warning(){}},getHostId:()=>hostId,getConversation:()=>conversation,dshSubmissionHead:()=>selectedHead,getThreadWorkspaceState:()=>pending,getThreadWritableRoots:async()=>[],readDefaultPersonality:cwd=>ctx.zan(requests,settings,cwd),getDefaultFeatureOverride:()=>false,getCodexHome:async()=>'/fixture/home',ensureDirectory:async()=>{calls.push('directory');},onNotification(){},updateTurnState(){}};
 const window={__DSH_EXECUTION_CONNECTED__:true,__DSH_EXECUTION_CONFIG_IDENTITY__:()=>({...identity})};
 ctx={console,structuredClone,AbortController,Set,Map,WeakMap,WeakSet,Object,client:manager,nativeClient:manager,window,navigator:{onLine:true},scope:{id:scope},executionEpoch:new Map(),userStopIntents:new Map(),submissionGeneration:0,hostPathEpoch:EPOCH,remoteServices:{},submissionReads:new Set(),waitForExecution:async()=>{},executionRead:requests.sendRequest,stoppingError:()=>Error('isolated stop'),
 kI:{},nE:'local',X_:x=>x!=='local',DMs:()=>false,kMs:()=>false,Vls:async()=>{},mYn:()=>[],aMs:()=>({input:{type:'text',text:'isolated fixture input'},responseItems:[]}),uMs:()=>[],PYn:()=>[],hAt:()=>false,IA:x=>x,Ig:()=>({approvalPolicy:'never',approvalsReviewer:'user',sandboxPolicy:{type:'dangerFullAccess'}}),Ng:x=>({sandboxPolicy:x.sandboxPolicy}),OMs:()=>false,iK:()=>null,Zx:10000,
 T:{debug(){},error(){}},kX(){},mCn:()=>({}),dan:{safeParse:value=>({success:value!=null&&typeof value==='object'&&!Array.isArray(value),data:value})},Sv:undefined,Vsn:()=>({applied:null,pendingRevision:pending?.pendingRevision,workspace:pending?.workspace??null}),Wsn:()=>[],Zsn:async()=>[],Gsn:async()=>!!projectless,ecn:async()=>projectless,Ksn:({currentWorkspaceKind,hasProjectlessWorkspace})=>hasProjectlessWorkspace?'projectless':currentWorkspaceKind,DS:()=>null,Pg:()=>({approvalPolicy:'never',sandboxPolicy:{type:'dangerFullAccess'}}),Fsn:x=>x,Hsn:x=>x,RC:(a,b)=>[...new Set([...a,...b])],Lsn:(_cwd,x)=>x,Isn:()=>false,Usn:()=>[],tcn:'explicitRequestOnly',GIn:'explicitRequestOnly',Xsn:()=>null,Qsn:x=>x,Ysn:()=>null};
 vm.createContext(ctx);vm.runInContext((source.includes('const dshHomeQueryAttempts=')?cut(source,'const dshHomeQueryAttempts=','function IMs('):'')+'globalThis.realOnResponse=function'+cut(source,'onResult(e,t,n){','onError(e,t,n){').slice('onResult'.length)+';'+cut(source,'function FC(','function lan(')+cut(source,'function uan(','var dan,fan=')+cut(source,'function Qjt(','var Cv=')+cut(source,'async function zan(','var Van=')+cut(source,'async function KPi(','var WW=')+cut(source,'const dshAttemptConfigs=new WeakMap();','async function EMs(')+cut(source,'function aan(','var can=')+cut(source,'async function jan(','var Man=')+cut(source,'async function Jsn(','function Ysn(')+cut(scopeSource,'client.dshReadExecutionHead=async id=>{','// Read-only quota facade'),ctx);
 const entryScope={get:()=>null};
 const prepare=async({freshHead=true,messageId=MSG,cwd=CWD}={})=>{if(freshHead)selectedHead=await manager.dshReadExecutionHead(A);const context={workspaceRoots:[cwd],imageAttachments:[],fileAttachments:[],pastedTextAttachments:[],addedFiles:[]};return ctx.TMs({scope:entryScope,manager,hostId,context,targetConversationId:A,cwd,agentMode:'auto',serviceTier:'priority',shouldSendPermissionOverrides:override,activeCollaborationMode:conversation.latestCollaborationMode,restoreMessage:{id:messageId,cwd,context},clientUserMessageId:messageId});};
 const consume=(operation,id=MSG)=>ctx.Jsn(manager,A,operation.start,id,null,conversation,{canUseProjectlessWorkspace:true,canMaterializeCodexHomeRoots:true,getAdditionalWritableRoots:()=>[],isSamePath:(a,b)=>a===b,getRequestCollaborationMode:x=>x,getRequestModel:x=>x,shouldShowModelChange:()=>false});
 return{calls,nativeCalls,fullConfig,conversation,manager,settings,ctx,identity,native,boundary,prepare,consume,head:()=>selectedHead,retire:()=>{current=false;ctx.submissionGeneration++;},replaceHead:()=>{selectedHead={...selectedHead};},changeHost:()=>{hostId='remote:fixture';requests.hostId=hostId;},allowFast:x=>{allowFast=x;},pending:x=>{pending=x;},projectless:x=>{projectless=x;}};
}
const reads=f=>f.calls.filter(x=>x?.method==='config/read');
sdkTest('production server DTO -> actual fresh head -> real TMs D=false -> Jsn uses exactly one config',async()=>{const f=fixture(),op=await f.prepare(),out=await f.consume(op);assert.equal(out.request.personality,'friendly');assert.equal(reads(f).length,1);assert.equal(f.nativeCalls.filter(x=>x.method==='config/read').length,1);assert.equal(out.request.serviceTier,'priority');assert.equal(out.request.collaborationMode.settings.model,'fixture-model');assert.equal(out.request.collaborationMode.settings.reasoning_effort,'high');assert.equal(f.calls.includes('directory'),false);assert.equal(f.head().configReadSnapshot.reply.config.model_reasoning_effort,'ultra');});
sdkTest('complete response DTO is immutable, exact, isolated, and not permission authorization',async()=>{const f=fixture(),op=await f.prepare(),head=f.head(),saved=head.configReadSnapshot.reply,before=JSON.stringify(saved);assert.equal(saved.configProjection.protocol,'dsh-scope-global-config-v1');assert.equal(saved.configProjection.scope,'ai');assert.equal(saved.configProjection.frontEpoch,EPOCH);assert.deepEqual(JSON.parse(JSON.stringify(saved.config.features)),f.fullConfig.features);assert.deepEqual(JSON.parse(JSON.stringify(saved.origins)),{});assert.throws(()=>{saved.config.features.safe_fixture.nested[0]=9;},TypeError);const token=op.start.context.dshAttemptConfig,snapshot=f.ctx.dshAttemptConfigs;const stored=vm.runInContext('dshAttemptConfigs',f.ctx).get(token);assert.notEqual(stored.configRead,saved);assert.equal(JSON.stringify(stored.configRead),before);assert.equal(stored.config.approval_policy,'never');assert.equal(stored.config.sandbox_mode,'danger-full-access');await f.consume(op);assert.equal(JSON.stringify(saved),before);assert.equal(f.calls.some(x=>x?.method==='turn/start'),false);});
sdkTest('fresh head per new attempt gets fresh Native read; same old head cannot reuse a second attempt',async()=>{const f=fixture(),a=await f.prepare();await f.consume(a);f.fullConfig.personality='pragmatic';const b=await f.prepare({messageId:'other-attempt'});assert.equal((await f.consume(b,'other-attempt')).request.personality,'pragmatic');assert.equal(reads(f).length,2);const c=await f.prepare({freshHead:false,messageId:'third-attempt'});await f.consume(c,'third-attempt');assert.equal(reads(f).length,3);});
sdkTest('one-use token and explicit/inherited persona retain semantics',async()=>{const f=fixture(),a=await f.prepare();await f.consume(a);f.fullConfig.personality='pragmatic';assert.equal((await f.consume(a)).request.personality,'pragmatic');assert.equal(reads(f).length,2);for(const kind of ['explicit','inherited']){const g=fixture(),p=await g.prepare();if(kind==='explicit')p.start.request.personality='pragmatic';else g.conversation.latestThreadSettings.personality='pragmatic';assert.equal((await g.consume(p)).request.personality,'pragmatic');assert.equal(reads(g).length,1);}});
for(const kind of ['protocol','frontEpoch','nativeGeneration','scope','transport','connection','resume','head','dispose','host','cwd','pending','clone','message','stop'])sdkTest('stale or semantically unmatched head falls back to real config: '+kind,async()=>{const f=fixture({allowProjection:kind!=='protocol'}),op=await f.prepare();f.fullConfig.personality='pragmatic';if(kind==='frontEpoch')f.identity.frontEpoch='other';if(kind==='nativeGeneration')f.identity.nativeGeneration++;if(kind==='scope')f.identity.scope='zyy';if(kind==='transport')f.identity.transportGeneration++;if(kind==='connection')f.identity.connectionId='other';if(kind==='resume')f.identity.resumeId='other';if(kind==='head')f.replaceHead();if(kind==='dispose')f.manager.disposed=true;if(kind==='host')f.changeHost();if(kind==='cwd')f.conversation.environments=[{cwd:CWD+'/agent',runtimeWorkspaceRoots:[]}];if(kind==='pending')f.pending({workspace:{cwd:CWD+'/agent',runtimeWorkspaceRoots:[]},pendingRevision:1});if(kind==='clone')op.start.context=JSON.parse(JSON.stringify(op.start.context));if(kind==='stop'){f.ctx.userStopIntents.set(A,{turnId:'old'});f.retire();}const out=await f.consume(op,kind==='message'?'different-message':MSG);assert.equal(out.request.personality,'pragmatic');assert.equal(reads(f).length,2);assert.equal(f.calls.some(x=>x?.method==='turn/start'),false);});
sdkTest('same scope-global read still requires matching canonical cwd after binding',async()=>{const f=fixture(),op=await f.prepare({cwd:CWD+'/./agent'});await f.consume(op);assert.equal(reads(f).length,2);});
sdkTest('Fast rejection still comes from live configRequirements, not saved config',async()=>{const f=fixture(),op=await f.prepare();f.allowFast(false);const out=await f.consume(op);assert.equal(out.request.serviceTier,null);assert.equal(reads(f).length,1);assert.equal(f.calls.filter(x=>x?.method==='configRequirements/read').length,1);});
sdkTest('invalid personality retains exact experiment fallback including failure',async()=>{const f=fixture({personality:'invalid'}),op=await f.prepare();assert.equal((await f.consume(op)).request.personality,'friendly');assert.equal(f.calls.filter(x=>x==='experiment').length,1);const g=fixture({personality:'invalid'}),p=await g.prepare();g.settings.readExperimentPersonality=()=>Promise.reject(Error('isolated experiment'));assert.equal((await g.consume(p)).request.personality,null);});
sdkTest('initial config failure prevents preparation, no hidden fresh fallback or write',async()=>{const error=Error('isolated config unavailable'),f=fixture({configError:error});await assert.rejects(f.prepare(),x=>x===error);assert.equal(reads(f).length,1);assert.equal(f.calls.some(x=>x?.method==='turn/start'),false);});
sdkTest('original explicit permission O branch still wins and is decoded once',async()=>{const f=fixture({override:true}),op=await f.prepare(),out=await f.consume(op);assert.equal(out.request.personality,'friendly');assert.equal(reads(f).length,2,'fresh head plus original cwd permission config; Jsn makes no third read');assert.equal(out.request.sandboxPolicy?.type??out.params.sandboxPolicy.type,'dangerFullAccess');});
sdkTest('server declaration only covers exact fixed-scope response and never stale generation',async()=>{const f=fixture(),reply=await f.boundary.call('ai',{id:'boundary-fixture',method:'config/read',params:{includeLayers:false,cwd:CWD}});assert.equal(reply.configProjection.cwdMode,'scope-global');assert.deepEqual(reply.config,f.fullConfig);const no=await f.boundary.call('ai',{id:'boundary-fixture2',method:'config/read',params:{includeLayers:true}});assert.equal(no.configProjection,undefined);const outside=await f.boundary.call('ai',{id:'boundary-fixture3',method:'config/read',params:{includeLayers:false,cwd:'/tmp'}});assert.equal(outside.configProjection,undefined);let gen=7;f.boundary.configProjectionIdentity=s=>({scope:s,frontEpoch:EPOCH,nativeGeneration:gen++});const stale=await f.boundary.call('ai',{id:'boundary-fixture4',method:'config/read',params:{includeLayers:false}});assert.equal(stale.configProjection,undefined);});

sdkTest('saved complete DTO cannot grant a different approval or sandbox policy at Front',async()=>{const f=fixture(),op=await f.prepare();await f.consume(op);await assert.rejects(f.boundary.call('ai',{id:'deny-fixture',method:'turn/start',params:{threadId:A,input:[],approvalPolicy:'on-request',sandboxPolicy:{type:'readOnly'}}},{clientId:'fixture-client'}),e=>e.code===403);assert.equal(f.nativeCalls.some(x=>x.method==='turn/start'),false);});

sdkTest('real negotiated scope identity helper reports only metadata and changes with wire lifetime',()=>{const wire={__dshGeneration:3,readyState:1,__dshHelloReceived:true,__dshBulkReadProtocol:'bulk-fixture',__dshReplyProtocol:'reply-fixture',__dshNativeConnected:true,__dshNativeGeneration:7,__dshFrontEpoch:EPOCH,__dshDiagnosticId:'connection-fixture'},window={},bridge={window,sockets:new Set([wire]),generation:3,scope:{id:'ai'},BULK_READ_PROTOCOL:'bulk-fixture',REPLY_STREAM_PROTOCOL:'reply-fixture',bulkAuthBlocked:false,blocked:false,loginRequired:false,resumeId:'resume-fixture'};vm.createContext(bridge);const state=cut(scopeSource,'function bulkState(){','// Small execution checks'),begin=scopeSource.indexOf(' window.__DSH_EXECUTION_METADATA_CONTROL_READY__=()=>'),end=scopeSource.indexOf(' function refreshBulkState',begin);assert(begin>=0&&end>begin);vm.runInContext(state+scopeSource.slice(begin,end),bridge);const a=window.__DSH_EXECUTION_CONFIG_IDENTITY__();assert.deepEqual(JSON.parse(JSON.stringify(a)),{scope:'ai',frontEpoch:EPOCH,nativeGeneration:7,transportGeneration:3,connectionId:'connection-fixture',resumeId:'resume-fixture'});assert(!Object.hasOwn(a,'token'));wire.__dshNativeGeneration=8;assert.notEqual(window.__DSH_EXECUTION_CONFIG_IDENTITY__().nativeGeneration,a.nativeGeneration);bridge.blocked=true;assert.equal(window.__DSH_EXECUTION_CONFIG_IDENTITY__(),null);});

sdkTest('new offline head rejects before Native reads and retired snapshot stays original fallback',async()=>{const f=fixture();f.ctx.waitForExecution=async()=>{if(!f.ctx.navigator.onLine)throw Error('fixture offline: no execution');};f.ctx.navigator.onLine=false;await assert.rejects(f.prepare(),/offline/);assert.equal(reads(f).length,0);assert.equal(f.nativeCalls.length,0);const g=fixture(),op=await g.prepare();g.ctx.navigator.onLine=false;g.fullConfig.personality='pragmatic';assert.equal((await g.consume(op)).request.personality,'pragmatic');assert.equal(reads(g).length,2,'snapshot cannot replace the original offline/read facade path');assert.equal(g.calls.some(x=>x?.method==='turn/start'),false);});

function installActualQueue(f){
 const queue=fs.readFileSync(process.env.DSH_HEAD_CONFIG_QUEUE||new URL('../public/native-queue-client.js',import.meta.url),'utf8');assert(scopeSource.includes(queue.trim()),'frozen final scope binds actual installNativeQueue module');
 delete f.manager.dshSubmissionHead;assert.equal(f.manager.dshSubmissionHead,undefined);
 const {manager,ctx}=f;manager.hostId='local';manager.inFlightConversationResumes=new Map();manager.pendingThreadSettingsUpdates=new Map();manager.addNotificationCallback=()=>{};manager.getStreamRole=()=>({role:'owner'});manager.needsResume=()=>false;manager.waitForPendingThreadSettingsUpdate=async()=>{};manager.resumeConversation=async()=>({status:'ready'});manager.settings={...manager.settings};
 f.conversation.id=A;f.conversation.resumeState='resumed';f.conversation.turns=[];
 const sent=[];manager.startTurn=async(id,operation)=>{sent.push({id,head:manager.dshSubmissionHead(id)});sent.at(-1).resolved=await f.consume({start:operation},operation.request.clientUserMessageId);return{turn:{id:'55555555-5555-4555-a555-555555555555'}};};manager.steerTurn=async()=>({turnId:'55555555-5555-4555-a555-555555555555'});
 Object.assign(ctx,{zx:class{},Ddn:[],ES:c=>c.turns.at(-1),wS:c=>c.turns,jS:c=>c.turns.at(-1),fun:()=>false,pun:()=>false,fv:()=>false,Edn(){},Adn:()=>false,Ybr:Symbol(),crypto:globalThis.crypto,location:{pathname:'/local/'+A},document:{visibilityState:'hidden',addEventListener(){}},URL,URLSearchParams,Response,CustomEvent,setTimeout,clearTimeout,setInterval:()=>1,clearInterval(){},addEventListener(){},removeEventListener(){},fetch:async()=>new Response(JSON.stringify({authority:'mac-native',state:{[A]:[]},revisions:{[A]:'fixture-revision'}}))});
 ctx.window.__DSH_SCOPE__={id:'ai',token:'fixture'};ctx.window.__DSH_NATIVE_ONLINE__=true;ctx.window.__DSH_NATIVE_CACHE__={meta:async()=>null,saveMeta:async()=>{},pendingCommands:async()=>[],recordCommand:async()=>{}};ctx.window.dispatchEvent=()=>{};
 vm.runInContext(cut(source,'async function EMs(','function DMs(')+';const Odn='+cut(source,'Odn=class extends zx{','}));function Adn(').slice(4)+';'+cut(source,'function Mdn(','var Ndn=')+';globalThis.coordinatorFactory=Mdn;',ctx);
 const q=ctx.coordinatorFactory(manager,{logger:manager.logger,storage:{readQueuedFollowUps:()=>({isLoading:false,value:{}})}},()=>{});manager.turnCoordinator=q;
 q.setMessagePreparation((request,kind)=>{assert(['start','steer'].includes(kind));return (kind==='start'?ctx.TMs:ctx.EMs)({scope:{get:()=>null},manager,hostId:'local',context:request.message.context,targetConversationId:request.conversationId,cwd:CWD,serviceTier:'priority',shouldSendPermissionOverrides:false,activeCollaborationMode:f.conversation.latestCollaborationMode,restoreMessage:request.message,clientUserMessageId:request.message.id});},async()=> 'send-now');
 vm.runInContext(queue,ctx);ctx.window.__DSH_INSTALL_NATIVE_QUEUE__(manager);assert.equal(typeof manager.dshSubmissionHead,'function');assert.equal(manager.dshSubmissionHead(A),undefined);
 const send=id=>q.sendMessage({conversationId:A,message:{id,text:'isolated fixture',cwd:CWD,context:{prompt:'isolated fixture',workspaceRoots:[CWD],imageAttachments:[],fileAttachments:[],pastedTextAttachments:[],addedFiles:[]}}});return{q,sent,send};
}
sdkTest('actual installNativeQueue getter and real SDK coordinator consume cache-produced head, no fixture getter',async()=>{const f=fixture(),q=installActualQueue(f);const result=await q.send(MSG);assert.equal(result.status,'sent');assert.equal(q.sent.length,1);assert.equal(q.sent[0].head.threadId,A);assert.equal(q.sent[0].head.configReadSnapshot.reply.configProjection.scope,'ai');assert.equal(q.sent[0].resolved.request.personality,'friendly');assert.equal(reads(f).length,1);assert.equal(f.manager.dshSubmissionHead(A),undefined,'attempt map retires after accepted return');f.fullConfig.personality='pragmatic';const second=await q.send('66666666-6666-4666-a666-666666666666');assert.equal(second.status,'sent');assert.equal(q.sent.length,2);assert.equal(q.sent[1].resolved.request.personality,'pragmatic');assert.equal(reads(f).length,2,'fresh second attempt, not cross-attempt cache');});
