import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(process.env.DSH_SUBMISSION_CACHE||new URL('../public/native-local-cache.js',import.meta.url),'utf8');
const A='11111111-1111-4111-a111-111111111111',TURN='22222222-2222-4222-a222-222222222222';
const cut=(a,b)=>{const i=source.indexOf(a),j=source.indexOf(b,i);assert(i>=0&&j>i,a);return source.slice(i,j);};
const execution=cut('const executionRead=async(method,params,options)=>{','client.dshReadResumeMetadata=');
const head=cut('client.dshReadExecutionHead=async id=>{','// Read-only quota facade');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});promise.catch(()=>{});return{promise,resolve,reject};};
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve));};
function fixture({status='idle',latest={id:TURN,status:'completed'},control=true,headGate=null,pageGate=null,configError=null,stop=null,before=false}={}){
 const reads=[],notes=[],updates=[],stops=new Map(stop?[[A,stop]]:[]),client={disposed:false,requestClient:{requestPromises:new Map()},getConversation:()=>({turns:[]}),onNotification:(method,params)=>notes.push({method,params}),updateTurnState:(id,turn,fn)=>{const t={};fn(t);updates.push({id,turn,t});}};
 const rpc=async(method,params,opts)=>{reads.push({method,params,priority:opts?.priority,lane:'control'});if(method==='thread/read'){if(headGate)await headGate.promise;return{thread:{id:A,status:{type:status,activeFlags:[]},threadSource:'user'}};}if(method==='config/read'){if(configError)throw configError;return{config:{sandbox_mode:'danger-full-access',approval_policy:'never'}};}if(method==='thread/turns/list'){if(pageGate)await pageGate.promise;return{data:latest?[latest]:[]};}throw Error('Unexpected write');};
 const window={__DSH_EXECUTION_CONNECTED__:true,__DSH_EXECUTION_METADATA_CONTROL_READY__:()=>control,__DSH_READ_EXECUTION_RPC__:async(m,p,o)=>{const index=reads.length,result=await rpc(m,p,o);reads[index].lane='http-bulk-metadata';return{status:200,result};}};
 const ctx={client,nativeClient:client,window,navigator:{onLine:true},AbortController,executionEpoch:new Map(),userStopIntents:stops,submissionGeneration:0,hostPathEpoch:0,remoteServices:{},submissionReads:new Set(),waitForExecution:async()=>{},original:rpc,stoppingError:()=>Object.assign(Error('isolated stop still pending'),{code:'DSH_TURN_STOPPING'})};
 let text=head;
 if(before){text=text.replace(',stoppingAtRead=userStopIntents.get(id)','');const a=text.indexOf('   let values,page=null;'),b=text.indexOf("   if(head.thread.status?.type==='active'",a);assert(a>=0&&b>a);text=text.slice(0,a)+"   let values;try{values=await Promise.race([Promise.all([read('thread/read',{threadId:id,includeTurns:false}),read('thread/turns/list',{threadId:id,limit:1,sortDirection:'desc',itemsView:'notLoaded'}),read('config/read',{includeLayers:false})]),retired]);}finally{submissionReads.delete(retire);}\n   if(values===null)return {isCurrent:()=>false};\n   const [head,page,policyRead]=values;\n   if(head?.thread?.id!==id||!Array.isArray(page?.data))throw Error('Current turn not verified');\n   const latest=page.data[0],activeTurnId=latest?.status==='inProgress'?latest.id:null;\n"+text.slice(b);text=text.replace('   if(stopping&&stopping!==stoppingAtRead)throw stoppingError();','');}
 vm.createContext(ctx);vm.runInContext(execution+text+';globalThis.run=()=>client.dshReadExecutionHead("'+A+'");globalThis.retire=()=>{submissionGeneration++;for(const fn of [...submissionReads])fn();};globalThis.changeSource=()=>{hostPathEpoch++;};',ctx);
 return{ctx,reads,notes,updates,stops,run:ctx.run,retire:ctx.retire,changeSource:ctx.changeSource};
}
test('old idle capture waits history; new idle decision never requests a rollout page',async()=>{const held=deferred(),old=fixture({before:true,pageGate:held}),work=old.run();let settled=false;work.then(()=>settled=true);await flush();assert.equal(settled,false);assert(old.reads.some(x=>x.method==='thread/turns/list'));old.retire();assert.equal((await work).isCurrent(),false);const next=fixture({pageGate:held}),head=await next.run();assert.equal(head.loaded,true);assert.equal(head.activeTurnId,null);assert.equal(head.hostPolicy.sandbox_mode,'danger-full-access');assert.deepEqual(next.reads.map(x=>x.method),['thread/read','config/read']);assert(next.reads.every(x=>x.priority==='critical'));assert.equal(next.notes.some(x=>x.method==='turn/completed'),false);});
test('notLoaded never becomes a writer/loaded grant or invents a current turn',async()=>{const f=fixture({status:'notLoaded'}),head=await f.run();assert.equal(head.loaded,false);assert.equal(head.activeTurnId,null);assert.equal(f.reads.some(x=>x.method==='thread/turns/list'),false);});
test('active and systemError still read exact metadata turn identity',async()=>{for(const status of ['active','systemError']){const f=fixture({status,latest:{id:TURN,status:'inProgress'}}),head=await f.run();assert.equal(head.activeTurnId,TURN);const page=f.reads.find(x=>x.method==='thread/turns/list');assert.deepEqual(JSON.parse(JSON.stringify(page.params)),{threadId:A,limit:1,sortDirection:'desc',itemsView:'notLoaded'});assert.equal(head.loaded,status==='active');}});
test('active with missing latest identity still rejects rather than silently starts',async()=>{const f=fixture({status:'active',latest:null});await assert.rejects(f.run(),/正在变化/);});
test('pending stop still checks same/newer Native turn and does not clear an unknown active stop',async()=>{const stop={turnId:TURN},blocked=fixture({status:'active',latest:{id:TURN,status:'inProgress'},stop});await assert.rejects(blocked.run(),/stop still pending/);assert.equal(blocked.stops.get(A),stop);const done=fixture({status:'idle',stop});await done.run();assert.equal(done.stops.has(A),false);assert(done.reads.some(x=>x.method==='thread/turns/list'));const newer=fixture({status:'active',latest:{id:'33333333-3333-4333-a333-333333333333',status:'inProgress'},stop});assert.notEqual((await newer.run()).activeTurnId,TURN);assert.equal(newer.stops.has(A),false);});
test('a newer stop while the head is pending cannot be cleared by the old idle capture',async()=>{const gate=deferred(),f=fixture({headGate:gate}),work=f.run();await flush();const stop={turnId:TURN};f.stops.set(A,stop);gate.resolve();await assert.rejects(work,/stop still pending/);assert.equal(f.stops.get(A),stop);});
test('reconnect retires held active/latest reads and cannot publish old capture',async()=>{const gate=deferred(),f=fixture({status:'active',pageGate:gate,latest:{id:TURN,status:'inProgress'}}),work=f.run();await flush();assert(f.reads.some(x=>x.method==='thread/turns/list'));f.retire();const head=await work;assert.equal(head.isCurrent(),false);gate.resolve();await flush();assert.equal(f.notes.length,0);});
test('source retirement after completion invalidates the same returned witness',async()=>{const f=fixture(),head=await f.run();assert.equal(head.isCurrent(),true);f.changeSource();assert.equal(head.isCurrent(),false);});
test('missing typed head never defaults idle; unknown state still consults actual turn metadata',async()=>{const missing=fixture({status:null});await assert.rejects(missing.run(),/尚未核实/);assert.equal(missing.reads.some(x=>x.method==='thread/turns/list'),false);const unknown=fixture({status:'unknown-native-state'}),head=await unknown.run();assert.equal(head.loaded,false);assert.equal(unknown.reads.some(x=>x.method==='thread/turns/list'),true);});
test('policy failure is still a preparation failure and fallback HTTP is typed metadata only',async()=>{const error=Error('isolated host policy unavailable'),f=fixture({configError:error});await assert.rejects(f.run(),x=>x===error);const h=fixture({control:false});await h.run();assert.deepEqual(h.reads.map(x=>x.lane),['http-bulk-metadata','http-bulk-metadata']);assert.equal(h.reads.some(x=>x.method==='thread/turns/list'),false);});
