import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {patchSameAttemptSubmissionConfig,patchFullAccessTurnDirectories} from '../src/official-submission-readiness.mjs';
const path=process.env.DSH_SUBMISSION_INITIAL||new URL('../../../runtime/critical-path-isolation-20261005/pass9/candidate/android-ui/files/official-patched-v1164/assets/app-initial-cadb12d4a15e.js',import.meta.url);
const before=await readFile(path,'utf8'),source=process.env.DSH_SUBMISSION_FINAL==='1'?before:patchSameAttemptSubmissionConfig(patchFullAccessTurnDirectories(before));
if(process.env.DSH_SUBMISSION_FINAL==='1'){assert(source.includes('const dshAttemptConfigs=new WeakMap();'));assert(source.includes('dshBindAttemptConfig(M.context,n,dshConfigHead'));}
const cut=(from,to)=>{const a=source.indexOf(from),b=source.indexOf(to,a);assert(a>=0&&b>a,from);return source.slice(a,b);};
const A='11111111-1111-4111-a111-111111111111',MSG='22222222-2222-4222-a222-222222222222';
function fixture({raw={personality:'friendly'},fresh={personality:'pragmatic'},override=true,host='local',cwd='/fixture/a',firstConfigGate=null}={}){
 const calls=[],head={threadId:A,isCurrent:()=>current},settings={readExperimentPersonality:async()=>{calls.push('experiment');return 'friendly';}};let current=true,selectedHead=head,stopping=false;
 const conversation={cwd,mode:'default',workspaceKind:'project',latestCollaborationMode:{mode:'default',settings:{model:'fixture-model',reasoning_effort:'high'}},latestModel:'fixture-model',latestReasoningEffort:'high',latestThreadSettings:{serviceTier:'priority'},currentPermissions:{approvalPolicy:'never',approvalsReviewer:'user',sandboxPolicy:{type:'dangerFullAccess'}}};
 const requests={hostId:host,sendRequest:async(method,params)=>{calls.push({method,params});if(method==='config/read'){const n=calls.filter(x=>x?.method==='config/read').length;if(fixtureConfigError&&n===1)throw fixtureConfigError;if(firstConfigGate&&n===1)await firstConfigGate.promise;return{config:n===1?raw:fresh};}if(method==='configRequirements/read')return{requirements:{featureRequirements:{fast_mode:allowFast}}};throw Error('Unexpected protocol write');}};
 let fixtureConfigError=null,allowFast=true,pending=null,projectless=null;
 const manager={disposed:false,requestClient:requests,sendRequest:requests.sendRequest,settings,logger:{info(){},warning(){}},getHostId:()=>host,getConversation:()=>conversation,dshSubmissionHead:()=>selectedHead,getThreadWorkspaceState:()=>pending,getThreadWritableRoots:async()=>[],readDefaultPersonality:cwd=>ctx.zan(requests,settings,cwd),getDefaultFeatureOverride:()=>false,getCodexHome:async()=>'/fixture/home',ensureDirectory:async()=>{calls.push('directory');}};
 const ctx={console,kI:{},nE:'local',X_:x=>x!=='local',DMs:()=>false,kMs:()=>false,Vls:async()=>{},mYn:()=>[],aMs:()=>({input:{type:'text',text:'isolated fixture input'},responseItems:[]}),uMs:()=>[],PYn:()=>[],hAt:()=>false,IA:x=>x,Ig:()=>({approvalPolicy:'never',approvalsReviewer:'user',sandboxPolicy:{type:'dangerFullAccess'}}),Ng:x=>({sandboxPolicy:x.sandboxPolicy}),OMs:()=>false,iK:()=>null,Zx:10000,
 dan:{safeParse:value=>({success:value!=null&&typeof value==='object'&&!Array.isArray(value),data:value})},Sv:undefined,
 Vsn:()=>({applied:null,pendingRevision:pending?.pendingRevision,workspace:pending?.workspace??null}),Wsn:()=>[],Zsn:async()=>[],Gsn:async()=>!!projectless,ecn:async()=>projectless,Ksn:({currentWorkspaceKind,hasProjectlessWorkspace})=>hasProjectlessWorkspace?'projectless':currentWorkspaceKind,DS:()=>null,Pg:()=>({approvalPolicy:'never',sandboxPolicy:{type:'dangerFullAccess'}}),Fsn:(value)=>value,Hsn:x=>x,RC:(a,b)=>[...new Set([...a,...b])],Lsn:(_cwd,x)=>x,Isn:()=>false,Usn:()=>[],tcn:'explicitRequestOnly',GIn:'explicitRequestOnly',Xsn:()=>null,Qsn:x=>x,Ysn:()=>null};
 vm.createContext(ctx);vm.runInContext(cut('function FC(','function lan(')+cut('function uan(','var dan,fan=')+cut('function Qjt(','var Cv=')+cut('async function zan(','var Van=')+cut('async function KPi(','var WW=')+cut('const dshAttemptConfigs=new WeakMap();','async function EMs(')+cut('function aan(','var can=')+cut('async function jan(','var Man=')+cut('async function Jsn(','function Ysn('),ctx);
 const scope={get:()=>null},context={workspaceRoots:[cwd],imageAttachments:[],fileAttachments:[],pastedTextAttachments:[],addedFiles:[]};
 const prepare=()=>ctx.TMs({scope,manager,hostId:host,context,targetConversationId:A,cwd,agentMode:'auto',serviceTier:'priority',shouldSendPermissionOverrides:override,activeCollaborationMode:conversation.latestCollaborationMode,restoreMessage:{id:MSG,cwd,context},clientUserMessageId:MSG});
 const personality=(operation,id=MSG)=>ctx.Jsn(manager,A,operation.start,id,null,conversation,{canUseProjectlessWorkspace:true,canMaterializeCodexHomeRoots:true,getAdditionalWritableRoots:()=>[],isSamePath:(a,b)=>a===b,getRequestCollaborationMode:x=>x,getRequestModel:x=>x,shouldShowModelChange:()=>false});
 return{calls,conversation,manager,settings,prepare,personality,ctx,setError:x=>{fixtureConfigError=x;},retire:()=>{current=false;},replaceHead:()=>{selectedHead={...head};},stop:()=>{stopping=true;current=false;},allowFast:x=>{allowFast=x;},pending:x=>{pending=x;},projectless:x=>{projectless=x;}};
}
const reads=f=>f.calls.filter(x=>x?.method==='config/read');
test('real TMs KPi profile-decoded config supplies only the same attempt Jsn default',async()=>{const f=fixture({raw:{personality:'friendly',profile:'chosen',profiles:{chosen:{personality:'pragmatic'}}}}),op=await f.prepare(),out=await f.personality(op);assert.equal(out.request.personality,'pragmatic');assert.equal(reads(f).length,1);assert.equal(out.request.serviceTier,'priority');assert.equal(out.request.sandboxPolicy?.type??out.params.sandboxPolicy.type,'dangerFullAccess');assert.equal(f.calls.includes('directory'),false);assert.deepEqual(JSON.parse(JSON.stringify(reads(f)[0].params)),{includeLayers:false,cwd:'/fixture/a'});});
test('same DTO retains model_personality and exact experiment fallback, including rejected experiment',async()=>{for(const raw of [{model_personality:'pragmatic'},{personality:'invalid'},{}]){const f=fixture({raw}),op=await f.prepare(),out=await f.personality(op);assert.equal(out.request.personality,raw.model_personality??'friendly');assert.equal(reads(f).length,1);}const f=fixture({raw:{}});f.settings.readExperimentPersonality=()=>Promise.reject(Error('isolated experiment'));assert.equal((await f.personality(await f.prepare())).request.personality,null);});
test('no permission config read and no matching cwd never acquire reuse authority',async()=>{const f=fixture({override:false}),op=await f.prepare();await f.personality(op);assert.equal(reads(f).length,1,'only original Ban executes');assert.equal(reads(f)[0].params.cwd,'/fixture/a');});
for(const kind of ['environment','pending','projectless','epoch','head','retired','otherAttempt','clonedContext','nonCanonical'])test('fresh Ban retained for '+kind,async()=>{const f=fixture({raw:{personality:'friendly'},fresh:{personality:'pragmatic'},cwd:kind==='nonCanonical'?'/fixture/./a':'/fixture/a'}),op=await f.prepare();if(kind==='environment')f.conversation.environments=[{cwd:'/fixture/b',runtimeWorkspaceRoots:[]}];if(kind==='pending')f.pending({workspace:{cwd:'/fixture/b',runtimeWorkspaceRoots:[]},pendingRevision:1});if(kind==='projectless')f.projectless({cwd:'/fixture/b',workspaceRoot:'/fixture'});if(kind==='epoch')f.retire();if(kind==='head')f.replaceHead();if(kind==='retired')f.manager.disposed=true;if(kind==='clonedContext')op.start.context={...op.start.context};const out=await f.personality(op,kind==='otherAttempt'?'other-message':MSG);assert.equal(reads(f).length,2);assert.equal(out.request.personality,'pragmatic');});
test('consumption is one-use, explicit and inherited personality still win',async()=>{const f=fixture({raw:{personality:'friendly'}}),op=await f.prepare();assert.equal((await f.personality(op)).request.personality,'friendly');assert.equal((await f.personality(op)).request.personality,'pragmatic');assert.equal(reads(f).length,2);for(const branch of ['explicit','inherited']){const g=fixture(),p=await g.prepare();if(branch==='explicit')p.start.request.personality='pragmatic';else g.conversation.latestThreadSettings.personality='pragmatic';assert.equal((await g.personality(p)).request.personality,'pragmatic');assert.equal(reads(g).length,1);}});
test('configuration failure, Fast requirements and Stop/epoch retirement keep original semantics',async()=>{const f=fixture(),error=Error('isolated configuration failure');f.setError(error);await assert.rejects(f.prepare(),x=>x===error);assert.equal(f.calls.some(x=>x?.method==='turn/start'),false);const g=fixture(),op=await g.prepare();g.allowFast(false);assert.equal((await g.personality(op)).request.serviceTier,null);const h=fixture(),p=await h.prepare();h.stop();await h.personality(p);assert.equal(reads(h).length,2);assert.equal(h.calls.some(x=>x?.method==='turn/start'),false);});
test('epoch replacement during the original configuration read cannot bind a stale DTO',async()=>{let release;const firstConfigGate={promise:new Promise(resolve=>release=resolve)},f=fixture({firstConfigGate}),work=f.prepare();for(let i=0;i<6;i++)await new Promise(resolve=>setImmediate(resolve));f.retire();release();await f.personality(await work);assert.equal(reads(f).length,2);});
test('normalized snapshot is not profile-decoded twice or mutable/serialized authority',async()=>{const raw={profile:'one',profiles:{one:{profile:'two',personality:'friendly'},two:{personality:'pragmatic'}}},f=fixture({raw}),op=await f.prepare();raw.profiles.one.personality='pragmatic';assert.equal((await f.personality(op)).request.personality,'friendly');const g=fixture(),p=await g.prepare();p.start.context=JSON.parse(JSON.stringify(p.start.context));await g.personality(p);assert.equal(reads(g).length,2);const h=fixture(),q=await h.prepare();q.start.context.dshAttemptConfig={config:{personality:'friendly'}};await h.personality(q);assert.equal(reads(h).length,2);});
test('nonlocal manager never reuses the local attempt capability',async()=>{const f=fixture({host:'remote:test'});await f.personality(await f.prepare());assert.equal(reads(f).length,2);assert.equal(reads(f)[1].params.cwd,null);});
test('patch is exact/idempotent and fails closed on changed SDK strings',()=>{assert.equal(patchSameAttemptSubmissionConfig(source),source);assert.throws(()=>patchSameAttemptSubmissionConfig('other SDK'),/contract changed/);});
