import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {patchParallelSubmissionReads,patchParallelTurnMetadata,patchFullAccessTurnDirectories} from '../src/official-submission-readiness.mjs';
const before=await readFile(process.env.DSH_PARALLEL_INITIAL||new URL('../../../runtime/critical-path-isolation-20261005/pass3/delivery-final/android-ui/files/official-patched-v1160/assets/app-initial-cadb12d4a15e.js',import.meta.url),'utf8');
const source=(process.env.DSH_PARALLEL_OLD==='1'||process.env.DSH_PARALLEL_FINAL==='1')?before:patchFullAccessTurnDirectories(patchParallelTurnMetadata(patchParallelSubmissionReads(before)));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(setImmediate);};
function fn(name){const a=source.indexOf('async function '+name+'(');assert(a>=0);const b=[source.indexOf('}function ',a),source.indexOf('}var ',a)].filter(n=>n>a);return source.slice(a,Math.min(...b)+1);}
function projectless(){const a=source.indexOf('async load(e=!1)'),b=source.indexOf('async hasConversationId',a);assert(a>0&&b>a);return vm.runInNewContext('({'+source.slice(a,b)+'})').load;}
test('fresh projectless membership and both path maps start in one read wave',async()=>{const calls=[],gate=deferred(),load=projectless();const host={hasFetchedConversationIds:false,conversationIds:new Set(['local']),outputDirectoryHints:new Map(),workspaceRootHints:new Map(),loadConversationIds(){calls.push('ids');return gate.promise.then(()=>new Set(['remote']));},loadThreadPathHints(key){calls.push(key);return gate.promise.then(()=>new Map([[key,'value']]));}};const work=load.call(host,true);await flush();assert.equal(calls.length,3);gate.resolve();assert.equal(await work,true);assert.deepEqual([...host.conversationIds],['remote']);assert.equal(host.hasFetchedConversationIds,true);});
test('failed membership does not commit separately successful hints',async()=>{const host={hasFetchedConversationIds:false,conversationIds:new Set(['kept']),outputDirectoryHints:new Map([['kept','old']]),workspaceRootHints:new Map(),loadConversationIds:async()=>null,loadThreadPathHints:async()=>new Map([['new','path']])};assert.equal(await projectless().call(host,true),false);assert.deepEqual([...host.outputDirectoryHints],[['kept','old']]);assert.equal(host.hasFetchedConversationIds,false);});
function config(proxy,read){const ctx={Djt:()=>({approvalPolicy:'never',sandboxPolicy:{type:'workspaceWrite'}}),Fbt:()=>['/allowed'],Ojt:'proxy',kjt:'fixture',proxy,read};vm.createContext(ctx);vm.runInContext(fn('Ejt')+';globalThis.run=()=>Ejt("model","fast",proxy,"/cwd",{approvalsReviewer:"user"},read,"friendly")',ctx);return ctx.run();}
test('proxy and host config fresh reads overlap and preserve request fields',async()=>{const gate=deferred(),calls=[];const work=config(()=>{calls.push('proxy');return gate.promise.then(()=>null);},()=>{calls.push('config');return gate.promise.then(()=>({'features.a':true}));});await flush();assert.deepEqual(calls,['proxy','config']);gate.resolve();const result=await work;assert.equal(result.serviceTier,'fast');assert.equal(result.approvalPolicy,'never');assert.equal(result.config['features.a'],true);assert.equal(result.cwd,'/cwd');});
test('proxy failure has original precedence and config rejection is observed',async()=>{const first=Error('proxy'),second=Error('config');await assert.rejects(config(async()=>{throw first;},async()=>{throw second;}),e=>e===first);await flush();});
test('configuration failure still rejects preparation',async()=>{const error=Error('policy');await assert.rejects(config(async()=>null,async()=>{throw error;}),e=>e===error);});
test('retained roots and projectless eligibility overlap before workspace materialization',async()=>{const start=source.indexOf('async function Jsn('),end=source.indexOf(',w=Ksn(',start);assert(start>0&&end>start);const gate=deferred(),calls=[],ctx={Vsn:()=>({applied:null,pendingRevision:0,workspace:null}),Wsn:()=>[],Gsn:async()=>{calls.push('membership');await gate.promise;return true;},Zsn:async()=>{calls.push('roots');await gate.promise;return ['/root'];},ecn:async({retainedWritableRoots})=>{calls.push('materialize');assert.deepEqual(retainedWritableRoots,['/root']);return {cwd:'/root'};},safeguard:gate};vm.createContext(ctx);vm.runInContext(source.slice(start,end)+';return {roots:_,workspace:C}};globalThis.run=()=>Jsn({getThreadWorkspaceState:()=>null},"thread",{request:{input:[]}},null,null,{cwd:"/root"},{canUseProjectlessWorkspace:true})',ctx);const work=ctx.run();await flush();assert.deepEqual(calls,['roots','membership']);gate.resolve();const result=await work;assert.equal(result.workspace.cwd,'/root');assert.deepEqual(calls,['roots','membership','materialize']);});
test('transform is idempotent and fails closed on changed renderer contract',()=>{assert.equal(patchParallelSubmissionReads(source),source);assert.throws(()=>patchParallelSubmissionReads('changed renderer'),/contract changed/);});

function turnMetadata({homeError=null,personalityError=null,tierError=null,allowFast=true,fullAccess=true,extraRoots=[]}={}){
 const a=source.indexOf('se=a.environments?.[0]?.environmentId'),b=source.indexOf(',Oe={threadId:t',a);assert(a>0&&b>a);const gate=deferred(),calls=[];
 const ctx={t:'fixture-thread',r:'fixture-message',a:{},s:{serviceTier:null},E:{serviceTier:'fast'},L:null,n:{context:{dshInheritTaskModel:true}},oe:{type:fullAccess?'dangerFullAccess':'workspaceWrite',writableRoots:['/cwd']},ne:{type:fullAccess?'dangerFullAccess':'workspaceWrite',writableRoots:['/cwd']},g:null,x:null,u:true,z:true,w:'regular',_:[],S:[],h:'/cwd',ae:'/cwd',m:null,H:[],Zx:10000,
 Qsn:p=>p,Lsn:(_cwd,v)=>v,RC:(a,b)=>[...new Set([...a,...b])],Isn:()=>false,
 o:{canMaterializeCodexHomeRoots:true,getAdditionalWritableRoots:()=>extraRoots},
 e:{logger:{warning(){}},getCodexHome:async()=>{calls.push('home');await gate.promise;if(homeError)throw homeError;return '/home';},ensureDirectory:async path=>{calls.push('mkdir:'+path);},readDefaultPersonality:async cwd=>{calls.push('personality');assert.equal(cwd,'/cwd');await gate.promise;if(personalityError)throw personalityError;return 'friendly';},sendRequest:async(method,params,opts)=>{calls.push('requirements');assert.equal(method,'configRequirements/read');assert.equal(params,undefined);assert.equal(opts.priority,'critical');assert.equal(opts.timeoutMs,10000);await gate.promise;if(tierError)throw tierError;return{requirements:{featureRequirements:{fast_mode:allowFast}}};}}};
 const helperStart=source.indexOf('const dshAttemptConfigs=new WeakMap();'),helperEnd=source.indexOf('async function TMs(',helperStart);
 const attemptHelpers=helperStart<0?'':source.slice(helperStart,helperEnd);
 vm.createContext(ctx);vm.runInContext(attemptHelpers+fn('jan')+';globalThis.run=async()=>{let '+source.slice(a,b)+';return{personality:we,serviceTier:De}};',ctx);return{ctx,calls,gate};
}
test('fresh personality, Fast requirements and filesystem preparation overlap after cwd resolution',async()=>{const f=turnMetadata(),work=f.ctx.run();await flush();assert.deepEqual([...f.calls].sort(),['home','personality','requirements']);f.gate.resolve();const result=await work;assert.equal(result.personality,'friendly');assert.equal(result.serviceTier,'fast','inherited task Fast wins over the composer default');});
test('Fast policy still disables the inherited tier before constructing a write',async()=>{const f=turnMetadata({allowFast:false}),work=f.ctx.run();f.gate.resolve();assert.equal((await work).serviceTier,null);});
test('filesystem and personality failures retain their original precedence over parallel Fast reads',async()=>{for(const values of [{homeError:Error('home'),personalityError:Error('personality'),tierError:Error('tier')},{personalityError:Error('personality'),tierError:Error('tier')}]){const f=turnMetadata(values),work=f.ctx.run();f.gate.resolve();await assert.rejects(work,e=>e===(values.homeError||values.personalityError));await flush();}});

test('full access sends preserve extra roots without any directory creation barrier',async()=>{const f=turnMetadata({extraRoots:['/home/worktrees','/home/scratchpad']}),work=f.ctx.run();f.gate.resolve();await work;assert.deepEqual(f.calls.filter(x=>x.startsWith('mkdir:')),[]);assert(f.calls.includes('requirements'));});
test('restricted workspace sends still prepare all required writable directories',async()=>{const f=turnMetadata({fullAccess:false,extraRoots:['/home/worktrees','/home/scratchpad']}),work=f.ctx.run();f.gate.resolve();await work;assert.deepEqual(f.calls.filter(x=>x.startsWith('mkdir:')),['mkdir:/home/worktrees','mkdir:/home/scratchpad']);});
