package top.whytan.dsh;
import static org.junit.Assert.*;
import android.content.Context;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.ExecutorService;
import org.json.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.robolectric.*;
import org.robolectric.annotation.Config;

/** Actual before/after Native DTOs from readonly SQLite; no Native or device operations. */
@RunWith(RobolectricTestRunner.class) @Config(sdk=28,manifest=Config.NONE)
public class ArchiveBodyIdentityTest {
 SyncStore store;SyncClient client;JSONObject fixtures;String id,source,generation;Context context;
 String hash(byte[] raw)throws Exception{StringBuilder out=new StringBuilder();for(byte x:MessageDigest.getInstance("SHA-256").digest(raw))out.append(String.format("%02x",x));return out.toString();}
 @Before public void setup()throws Exception{context=RuntimeEnvironment.getApplication();context.deleteDatabase("native-sync-v1.sqlite");store=new SyncStore(context);byte[] raw=Files.readAllBytes(Paths.get(System.getProperty("dsh.body.identity.fixture",PublicNativeFixtures.file("identity"))));assertEquals("d9d9d03a6d8ad6891a4e85e273e3541dcb21addea631188661ff0be0a77618f8",hash(raw));fixtures=new JSONObject(new String(raw,StandardCharsets.UTF_8));JSONObject initial=fixtures.getJSONObject("native69-initial");id=initial.getJSONArray("records").getJSONObject(0).getString("threadId");source=initial.getJSONObject("progress").getString("sourceGeneration");generation=initial.getJSONObject("progress").getString("generation");install(initial);store.saveArchiveProgress("ai",id,new JSONObject(initial.getJSONObject("progress").toString()));}
 @After public void close(){if(client!=null)client.close();store.close();}
 void install(JSONObject input)throws Exception{JSONArray records=input.getJSONArray("records");for(int i=0;i<records.length();i++)store.applyNativeRecord(new JSONObject(records.getJSONObject(i).toString()));JSONArray pages=input.getJSONArray("latestArchivePages");for(int i=0;i<pages.length();i++)store.saveReadRecord("ai",new JSONObject(pages.getJSONObject(i).toString()));}
 JSONObject selected(JSONObject input,String method)throws Exception{JSONArray records=input.getJSONArray("records");for(int i=0;i<records.length();i++){JSONObject r=records.getJSONObject(i),p=r.optJSONObject("payload");if(method.equals("catalog")&&"catalog".equals(r.optString("kind"))||p!=null&&method.equals(p.optString("method")))return new JSONObject(r.toString());}throw new AssertionError("exact producer record missing");}
 JSONObject summary()throws Exception{return selected(fixtures.getJSONObject("native69-initial"),"thread/turns/list");}
 String version(){return store.historyPreparationVersion("ai",id);}
 void client()throws Exception{client=new SyncClient(context,"ai",store,new SyncClient.Listener(){public void onState(String s,JSONObject v){}public void onCompletion(String s,String t,String u,boolean r){}});for(String n:new String[]{"prefetchWorkers","focusWorkers"}){Field f=SyncClient.class.getDeclaredField(n);f.setAccessible(true);((ExecutorService)f.get(client)).shutdownNow();}}
 void schedule()throws Exception{Method m=SyncClient.class.getDeclaredMethod("scheduleArchive",String.class);m.setAccessible(true);m.invoke(client,id);}
 @Test public void realLegacyCompleteArchiveMigratesOnlyWithExactNativeEofBodyCoverage()throws Exception{String v=version();assertTrue(v.startsWith("body-v1:"));assertTrue(store.archivePrepared("ai",id,v));assertTrue(store.archiveProgress("ai",id).getBoolean("complete"));assertEquals(9,store.archiveProgress("ai",id).getInt("turnIndex"));store.close();store=new SyncStore(context);assertTrue(store.archivePrepared("ai",id,version()));}
 @Test public void realViewTouchDoesNotRestartFullyArchivedUnchangedNativeBody()throws Exception{String before=version();assertTrue(store.archivePrepared("ai",id,before));JSONObject after=fixtures.getJSONObject("native69-after2");install(after);JSONObject s=selected(after,"thread/turns/list");assertEquals(SyncStore.readPayloadDigest(summary().getJSONObject("payload").getJSONObject("result").getJSONArray("data")),SyncStore.readPayloadDigest(s.getJSONObject("payload").getJSONObject("result").getJSONArray("data")));store.noteVerifiedBodySummaryRead(s,store.historyBodyFence("ai",id));assertEquals(before,version());client();schedule();assertTrue(store.duePreparations("ai",Long.MAX_VALUE,20).stream().noneMatch(x->x.kind.equals("archive")));assertEquals(9,store.archiveProgress("ai",id).getInt("turnIndex"));assertTrue(store.archiveProgress("ai",id).getBoolean("complete"));}
 @Test public void timestampChangeWithoutFreshBodyProofOnlyRequestsShortVerification()throws Exception{assertTrue(store.archivePrepared("ai",id,version()));JSONObject catalog=selected(fixtures.getJSONObject("native69-after2"),"catalog");store.applyNativeRecord(catalog);assertTrue(version().startsWith("verify-body-v1:"));client();schedule();assertTrue(store.duePreparations("ai",Long.MAX_VALUE,20).stream().anyMatch(x->x.kind.equals("history")));assertTrue(store.duePreparations("ai",Long.MAX_VALUE,20).stream().noneMatch(x->x.kind.equals("archive")));assertTrue(store.archiveProgress("ai",id).getBoolean("complete"));}
 @Test public void realNewUserOrNewTurnCannotReuseOldArchive()throws Exception{String old=version();assertTrue(store.archivePrepared("ai",id,old));JSONObject next=summary().put("revision",900000);JSONObject turn=next.getJSONObject("payload").getJSONObject("result").getJSONArray("data").getJSONObject(0);turn.put("id","33333333-3333-4333-8333-333333333333");turn.getJSONArray("items").put(new JSONObject().put("id","new-input").put("type","userMessage").put("content",new JSONArray().put(new JSONObject().put("type","text").put("text","SYNTHETIC_NEW_INPUT"))));store.applyNativeRecord(next);store.noteVerifiedBodySummaryRead(next,0);assertNotEquals(old,version());assertFalse(store.archivePrepared("ai",id,version()));}
 @Test public void changedSameIdOriginalInputAndFinalTextInvalidateBodyIdentity()throws Exception{String old=version();assertTrue(store.archivePrepared("ai",id,old));JSONObject next=summary().put("revision",900000);JSONArray items=next.getJSONObject("payload").getJSONObject("result").getJSONArray("data").getJSONObject(0).getJSONArray("items");JSONObject user=null,finalItem=null;for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);if("userMessage".equals(item.optString("type")))user=item;if("agentMessage".equals(item.optString("type")))finalItem=item;}assertNotNull(user);assertNotNull(finalItem);user.put("content",new JSONArray().put(new JSONObject().put("type","text").put("text","SYNTHETIC_CHANGED_INPUT")));finalItem.put("text","SYNTHETIC_CHANGED_FINAL");store.applyNativeRecord(next);store.noteVerifiedBodySummaryRead(next,0);assertNotEquals(old,version());assertFalse(store.archivePrepared("ai",id,version()));}
 @Test public void rewriteAndForeignSourceCannotBorrowPriorCompleteArchive()throws Exception{assertTrue(store.archivePrepared("ai",id,version()));JSONObject c=selected(fixtures.getJSONObject("native69-initial"),"catalog").put("revision",900000).put("generation","rewrite");store.applyNativeRecord(c);assertFalse(store.archivePrepared("ai",id,version()));store.resetGeneration("ai","foreign");assertFalse(store.archivePrepared("ai",id,version()));assertFalse(store.archivePrepared("zyy",id,version()));}
 @Test public void activeOrUnknownCurrentMetadataNeverConfirmsOldCompleteBody()throws Exception{String old=version();assertTrue(store.archivePrepared("ai",id,old));JSONObject c=selected(fixtures.getJSONObject("native69-initial"),"catalog").put("revision",900000);c.getJSONObject("payload").getJSONObject("nativeThread").put("status",new JSONObject().put("type","active"));store.applyNativeRecord(c);assertTrue(store.archiveBodyVersion("ai",id).isEmpty());c.put("revision",900001);c.getJSONObject("payload").getJSONObject("nativeThread").remove("status");store.applyNativeRecord(c);assertTrue(store.archiveBodyVersion("ai",id).isEmpty());assertFalse(store.archivePrepared("ai",id,old));}
 @Test public void controlStatusAndEpochSequenceDoNotChangeConfirmedBodyIdentity()throws Exception{String old=version();assertTrue(store.archivePrepared("ai",id,old));store.observeHistoryBodyEvent("ai",new JSONObject().put("type","status").put("threadId",id).put("status",new JSONObject().put("type","idle")).put("deliveryVersion","new-epoch:999"));store.observeHistoryBodyEvent("ai",new JSONObject().put("type","nativeChanged").put("threadId",id).put("cacheKey","thread:"+id).put("deliveryVersion","new-epoch:1000"));assertEquals(old,version());assertTrue(store.archivePrepared("ai",id,old));}
 @Test public void compactionOrActualBodyInvalidationRequiresNewNativeProof()throws Exception{String old=version();assertTrue(store.archivePrepared("ai",id,old));store.observeHistoryBodyEvent("ai",new JSONObject().put("type","nativeChanged").put("threadId",id).put("cacheKey","invalidate:"+id).put("deliveryVersion","body-epoch:1"));assertTrue(version().startsWith("verify-body-v1:"));assertFalse(store.archivePrepared("ai",id,old));JSONObject s=summary().put("revision",900000);store.applyNativeRecord(s);store.noteVerifiedBodySummaryRead(s,store.historyBodyFence("ai",id));assertNotEquals(old,version());assertFalse(store.archivePrepared("ai",id,version()));}
 @Test public void incompleteOrMissingEofPagesCannotBeUpgradedToComplete()throws Exception{JSONObject p=store.archiveProgress("ai",id).put("complete",false).put("turnIndex",3);store.saveArchiveProgress("ai",id,p);assertFalse(store.archivePrepared("ai",id,version()));p.put("complete",true);store.saveArchiveProgress("ai",id,p);store.getWritableDatabase().delete("saved_records","scope=? AND thread_id=? AND key LIKE ?",new String[]{"ai",id,"read:[\"thread/items/list\",%"});assertFalse(store.archivePrepared("ai",id,version()));assertFalse(store.archiveProgress("ai",id).has("bodyVersion"));}
 @Test public void bodyEventDuringReadCannotBeCoveredByLateOldSummary()throws Exception{long fence=store.historyBodyFence("ai",id);store.observeHistoryBodyEvent("ai",new JSONObject().put("type","item").put("threadId",id).put("turnId","33333333-3333-4333-8333-333333333333").put("item",new JSONObject().put("id","new-user").put("type","userMessage").put("content",new JSONArray())));store.noteVerifiedBodySummaryRead(summary(),fence);assertTrue(version().startsWith("verify-body-v1:"));assertFalse(store.archivePrepared("ai",id,version()));}
}
