package top.whytan.dsh;
import static org.junit.Assert.*;
import android.content.Context;
import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.io.IOException;
import okhttp3.*;
import org.json.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.robolectric.*;
import org.robolectric.annotation.Config;
/** Explicit synthetic paginator exercises the actual worker; does not claim live Native cursor acceptance. */
@RunWith(RobolectricTestRunner.class) @Config(sdk=28,manifest=Config.NONE)
public class DeepArchivePageSizeTest {
 static final String ID="11111111-1111-4111-8111-111111111111",TURN="22222222-2222-4222-8222-222222222222";
 SyncStore store;SyncClient client;List<String> cursors=new ArrayList<>();List<Integer> limits=new ArrayList<>();int revision;
 @Before public void setup()throws Exception{Context c=RuntimeEnvironment.getApplication();c.deleteDatabase("native-sync-v1.sqlite");store=new SyncStore(c);store.saveCatalogCursor("ai","g1",0);JSONObject turn=new JSONObject().put("id",TURN).put("status","completed").put("items",new JSONArray());store.saveArchiveProgress("ai",ID,new JSONObject().put("sourceGeneration","g1").put("generation","g1").put("desired","owned-fixture").put("complete",false).put("turns",new JSONArray().put(turn)).put("turnIndex",0).put("nextTurnCursor",JSONObject.NULL));client=new SyncClient(c,"ai",store,new SyncClient.Listener(){public void onState(String s,JSONObject v){}public void onCompletion(String s,String t,String u,boolean r){}});for(String n:new String[]{"prefetchWorkers","focusWorkers"}){Field f=SyncClient.class.getDeclaredField(n);f.setAccessible(true);((ExecutorService)f.get(client)).shutdownNow();}OkHttpClient mock=new OkHttpClient.Builder().addInterceptor(chain->{try{okio.Buffer b=new okio.Buffer();chain.request().body().writeTo(b);JSONObject request=new JSONObject(b.readUtf8()),params=request.getJSONObject("params"),result=new JSONObject();String method=request.getString("method");if("thread/read".equals(method))result.put("thread",new JSONObject().put("id",ID).put("historyMode","paginated").put("status",new JSONObject().put("type","idle")));else{assertEquals("thread/items/list",method);assertEquals(12,params.getInt("limit"));limits.add(params.getInt("limit"));String cursor=params.optString("cursor",null);cursors.add(cursor);JSONArray items=new JSONArray();int from=cursor==null?24:12;for(int i=from;i>from-12;i--)items.put(new JSONObject().put("item",new JSONObject().put("id","item-"+i).put("type","commandExecution").put("aggregatedOutput","SYNTHETIC_COMPLETE_OUTPUT_"+i)));result.put("data",items).put("nextCursor",cursor==null?"owned-next-page":JSONObject.NULL);}List<String> keys=new ArrayList<>();params.keys().forEachRemaining(keys::add);Collections.sort(keys);JSONObject sorted=new JSONObject();for(String key:keys)sorted.put(key,params.get(key));JSONObject record=new JSONObject().put("scope","ai").put("threadId",ID).put("key","read:"+new JSONArray().put(method).put(sorted).toString().replace("\\/","/")).put("kind","history").put("sourceGeneration","g1").put("generation","g1").put("revision",++revision).put("deleted",false).put("payload",new JSONObject().put("method",method).put("params",params).put("result",result));return new Response.Builder().request(chain.request()).protocol(Protocol.HTTP_1_1).code(200).message("fixture").body(ResponseBody.create(record.toString(),MediaType.get("application/json"))).build();}catch(Exception e){throw new IOException(e);}}).build();Field f=SyncClient.class.getDeclaredField("http");f.setAccessible(true);f.set(client,mock);}
 @After public void close(){client.close();store.close();}
 boolean batch()throws Exception{Method m=SyncClient.class.getDeclaredMethod("archiveHistoryBatch",String.class,String.class,String.class);m.setAccessible(true);return (Boolean)m.invoke(client,ID,UUID.randomUUID().toString(),"owned-fixture");}
 @Test public void deepTwelveItemPagesKeepCursorOrderEofAndEveryOriginalField()throws Exception{assertFalse(batch());assertEquals(Arrays.asList(12,12),limits);assertEquals(Arrays.asList(null,"owned-next-page"),cursors);JSONObject progress=store.archiveProgress("ai",ID);assertEquals(1,progress.getInt("turnIndex"));assertFalse(progress.has("itemCursor"));assertFalse(progress.getBoolean("complete"));assertTrue(batch());assertTrue(store.archiveProgress("ai",ID).getBoolean("complete"));Set<String> ids=new HashSet<>();try(android.database.Cursor rows=store.getReadableDatabase().rawQuery("SELECT payload FROM saved_records WHERE scope=? AND thread_id=? AND key LIKE ?",new String[]{"ai",ID,"read:[\"thread/items/list\",%"})){while(rows.moveToNext()){JSONArray items=new JSONObject(rows.getString(0)).getJSONObject("result").getJSONArray("data");assertEquals(12,items.length());for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i).getJSONObject("item");String id=item.getString("id");assertTrue(ids.add(id));assertEquals("SYNTHETIC_COMPLETE_OUTPUT_"+id.substring(5),item.getString("aggregatedOutput"));}}}assertEquals(24,ids.size());}
}
